# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/analytics/a_rpc.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'io/common/reporting_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/analytics/a_rpc.proto", :syntax => :proto3) do
  end
end

module Analytics
end
