# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/attributes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/attributes.proto", :syntax => :proto3) do
    add_enum "io.DeviceAttributes" do
      value :NoAttributes, 0
      value :Ios, 1
      value :Android, 2
      value :SupportWallet, 4
      value :WalletScanner, 8
      value :WalletDaemon, 16
      value :WalletPasses, 32
      value :Windows, 64
      value :OSX, 128
      value :Linux, 256
      value :Mobile, 512
      value :Desktop, 1024
      value :Tablet, 2048
      value :UnsupportedIos, 4096
    end
  end
end

module Io
  DeviceAttributes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DeviceAttributes").enummodule
end
