# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/billing.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/billing.proto", :syntax => :proto3) do
    add_message "io.Quota" do
      map :details, :uint32, :message, 1, "io.QuotaDetails"
    end
    add_message "io.QuotaDetails" do
      optional :quota, :int32, 1
      optional :status, :uint64, 2
    end
  end
end

module Io
  Quota = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Quota").msgclass
  QuotaDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.QuotaDetails").msgclass
end
