# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/callback.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/callback.proto", :syntax => :proto3) do
    add_message "io.Callback" do
      optional :event, :enum, 1, "io.CallbackEvent"
      optional :type, :enum, 2, "io.CallbackType"
      optional :receiver, :string, 3
    end
    add_enum "io.CallbackEvent" do
      value :CALLBACK_OBJECT_CREATED, 0
      value :CALLBACK_OBJECT_UPDATED, 1
      value :CALLBACK_OBJECT_REMOVED, 2
      value :CALLBACK_PASS_ISSUED, 3
      value :CALLBACK_PASS_INSTALLED, 4
      value :CALLBACK_PASS_UPDATED, 5
      value :CALLBACK_PASS_REMOVED, 6
      value :EMAIL_OPENED, 7
      value :LINK_VISITED, 8
    end
    add_enum "io.CallbackType" do
      value :CALLBACK_TYPE_SEND_EMAIL, 0
      value :CALLBACK_TYPE_SEND_SMS, 1
      value :CALLBACK_TYPE_SEND_POST, 2
      value :CALLBACK_TYPE_INTEGRATION, 3
    end
  end
end

module Io
  Callback = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Callback").msgclass
  CallbackEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.CallbackEvent").enummodule
  CallbackType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.CallbackType").enummodule
end
