# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/distribution.proto

require 'google/protobuf'

require 'io/common/common_objects_pb'
require 'io/common/localization_pb'
require 'io/common/protocols_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/distribution.proto", :syntax => :proto3) do
    add_message "io.EmailDistributionRequest" do
      optional :id, :string, 1
      optional :protocol, :enum, 2, "io.PassProtocol"
      optional :alternativeEmail, :string, 3
    end
    add_message "io.SmartPassLinkRequest" do
      optional :projectDistributionUrl, :message, 1, "io.Url"
      map :fields, :string, :string, 2
    end
    add_message "io.DistributionSettings" do
      repeated :distributionChannels, :enum, 1, "io.DistributionChannel"
      optional :welcomeEmail, :message, 2, "io.EmailTemplate"
      optional :welcomeSms, :message, 3, "io.SmsTemplate"
    end
    add_message "io.EmailTemplate" do
      optional :subject, :string, 1
      optional :localizedSubject, :message, 2, "io.LocalizedString"
      optional :bodyTextContent, :string, 3
      optional :localizedBodyTextContent, :message, 4, "io.LocalizedString"
      optional :bodyHtmlContent, :string, 5
      optional :localizedBodyHtmlContent, :message, 6, "io.LocalizedString"
      optional :configuration, :message, 7, "io.EmailConfiguration"
      optional :buttonText, :string, 8
      optional :buttonTextColor, :string, 9
      optional :buttonBackgroundColor, :string, 10
      optional :buttonBorderRadius, :string, 11
      optional :footerTextContent, :string, 12
      optional :localizedFooterTextContent, :message, 13, "io.LocalizedString"
      optional :footerHtmlContent, :string, 14
      optional :localizedFooterHtmlContent, :message, 15, "io.LocalizedString"
      optional :messageBackgroundColor, :string, 16
      optional :pageBackgroundColor, :string, 17
    end
    add_message "io.EmailConfiguration" do
      optional :emailFrom, :string, 1
      optional :emailFromName, :string, 2
      optional :EmailFromVerifiedForSending, :bool, 3
    end
    add_message "io.SmsTemplate" do
      optional :content, :string, 1
      optional :localizedContent, :message, 2, "io.LocalizedString"
    end
    add_enum "io.DistributionChannel" do
      value :NO_DISTRIBUTION, 0
      value :CHANNEL_EMAIL, 1
      value :CHANNEL_SMS, 2
    end
  end
end

module Io
  EmailDistributionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.EmailDistributionRequest").msgclass
  SmartPassLinkRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.SmartPassLinkRequest").msgclass
  DistributionSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DistributionSettings").msgclass
  EmailTemplate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.EmailTemplate").msgclass
  EmailConfiguration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.EmailConfiguration").msgclass
  SmsTemplate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.SmsTemplate").msgclass
  DistributionChannel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DistributionChannel").enummodule
end
