# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/expiry.proto

require 'google/protobuf'

require 'io/common/common_objects_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/expiry.proto", :syntax => :proto3) do
    add_message "io.ExpirySettings" do
      optional :expiryType, :enum, 1, "io.ExpiryType"
      oneof :expiryOneof do
        optional :fixedExpiryDate, :message, 2, "io.Date"
        optional :expireAfterXDays, :uint32, 3
      end
    end
    add_enum "io.ExpiryType" do
      value :EXPIRE_NONE, 0
      value :EXPIRE_ON_FIXED_DATE, 1
      value :EXPIRE_AFTER_X_DAYS, 2
      value :EXPIRE_ON_VARIABLE_DATE_TIME, 3
      value :EXPIRE_SET_TO_NULL, 4
    end
  end
end

module Io
  ExpirySettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.ExpirySettings").msgclass
  ExpiryType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.ExpiryType").enummodule
end
