# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/filter.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/filter.proto", :syntax => :proto3) do
    add_message "io.Filters" do
      optional :limit, :int32, 1
      optional :offset, :int32, 2
      repeated :filterGroups, :message, 3, "io.FilterGroup"
      optional :orderBy, :string, 4
      optional :orderAsc, :bool, 5
    end
    add_message "io.FieldFilter" do
      optional :filterField, :string, 1
      optional :filterValue, :string, 2
      optional :filterOperator, :string, 3
    end
    add_message "io.FilterGroup" do
      optional :condition, :enum, 1, "io.Operator"
      repeated :fieldFilters, :message, 2, "io.FieldFilter"
    end
    add_enum "io.Operator" do
      value :AND, 0
      value :OR, 1
    end
  end
end

module Io
  Filters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Filters").msgclass
  FieldFilter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.FieldFilter").msgclass
  FilterGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.FilterGroup").msgclass
  Operator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Operator").enummodule
end
