# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/job.proto

require 'google/protobuf'

require 'io/common/protocols_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/job.proto", :syntax => :proto3) do
    add_message "io.Job" do
      optional :id, :string, 1
      optional :username, :string, 2
      optional :protocol, :enum, 3, "io.PassProtocol"
      optional :status, :enum, 4, "io.JobStatus"
      optional :type, :enum, 5, "io.JobType"
      optional :schedule, :message, 6, "io.Schedule"
      optional :created, :message, 7, "google.protobuf.Timestamp"
      optional :updated, :message, 8, "google.protobuf.Timestamp"
      optional :firstRun, :message, 9, "google.protobuf.Timestamp"
      optional :finalRun, :message, 10, "google.protobuf.Timestamp"
      optional :nextRun, :message, 11, "google.protobuf.Timestamp"
      optional :lastRun, :message, 12, "google.protobuf.Timestamp"
    end
    add_message "io.CompletedJob" do
      optional :id, :string, 1
      optional :cid, :string, 2
      optional :uid, :string, 3
      optional :protocol, :enum, 4, "io.PassProtocol"
      optional :type, :enum, 5, "io.JobType"
      optional :status, :enum, 6, "io.JobStatus"
      optional :details, :string, 7
      optional :completed, :message, 8, "google.protobuf.Timestamp"
      oneof :CompletedJobOutput do
        optional :completedCsvImport, :message, 9, "io.CompletedCsvImport"
      end
    end
    add_message "io.CompletedCsvImport" do
      optional :fileUrl, :string, 1
    end
    add_message "io.Schedule" do
      optional :cronTabSchedule, :string, 1
      optional :repeating, :bool, 2
      optional :timezone, :string, 3
      optional :startTime, :message, 4, "google.protobuf.Timestamp"
      optional :runUntil, :message, 5, "google.protobuf.Timestamp"
    end
    add_message "io.CsvImportRequest" do
      optional :classId, :string, 1
      optional :protocol, :enum, 2, "io.PassProtocol"
      optional :fileBytes, :bytes, 3
    end
    add_enum "io.JobStatus" do
      value :JOB_SCHEDULED, 0
      value :JOB_RUNNING, 1
      value :JOB_PAUSED, 2
      value :JOB_COMPLETED, 3
      value :JOB_COMPLETED_WITH_ERRORS, 4
    end
    add_enum "io.JobType" do
      value :JOB_CSV_IMPORT, 0
      value :JOB_CSV_EXPORT, 1
    end
  end
end

module Io
  Job = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Job").msgclass
  CompletedJob = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.CompletedJob").msgclass
  CompletedCsvImport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.CompletedCsvImport").msgclass
  Schedule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Schedule").msgclass
  CsvImportRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.CsvImportRequest").msgclass
  JobStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.JobStatus").enummodule
  JobType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.JobType").enummodule
end
