# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/links.proto

require 'google/protobuf'

require 'io/common/common_objects_pb'
require 'io/common/localization_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/links.proto", :syntax => :proto3) do
    add_message "io.Link" do
      optional :id, :string, 1
      optional :url, :string, 2
      optional :title, :string, 3
      optional :type, :enum, 4, "io.LinkType"
      optional :localizedLink, :message, 5, "io.LocalizedString"
      optional :localizedTitle, :message, 6, "io.LocalizedString"
      repeated :usage, :enum, 7, "io.UsageType"
      optional :position, :uint32, 8
    end
    add_message "io.DbLink" do
      repeated :links, :message, 1, "io.Link"
    end
    add_enum "io.LinkType" do
      value :URI_DO_NOT_USE, 0
      value :URI_WEB, 1
      value :URI_TEL, 2
      value :URI_EMAIL, 3
      value :URI_LOCATION, 4
      value :URI_CALENDAR, 5
    end
  end
end

module Io
  Link = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Link").msgclass
  DbLink = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DbLink").msgclass
  LinkType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.LinkType").enummodule
end
