# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/localization.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/localization.proto", :syntax => :proto3) do
    add_message "io.LocalizedString" do
      map :translations, :string, :string, 1
    end
    add_enum "io.LanguageCode" do
      value :EN, 0
      value :AR, 4
      value :ZH_HANS, 8
      value :ZH_HANT, 12
      value :ZH_HK, 16
      value :CA, 20
      value :HR, 24
      value :CS, 28
      value :DA, 32
      value :DE, 36
      value :EN_AU, 40
      value :EN_GB, 44
      value :EN_CA, 48
      value :EN_US, 52
      value :EN_IN, 56
      value :ES, 60
      value :ES_419, 64
      value :FI, 68
      value :FR, 72
      value :FR_CA, 76
      value :EL, 80
      value :HE, 84
      value :HI, 88
      value :HU, 92
      value :ID, 96
      value :IT, 100
      value :JA, 104
      value :KO, 108
      value :MS, 112
      value :MT, 116
      value :NL, 120
      value :NB, 124
      value :PL, 128
      value :PT, 132
      value :PT_BR, 136
      value :RO, 140
      value :RU, 144
      value :SK, 148
      value :SV, 152
      value :TH, 156
      value :TR, 160
      value :UK, 164
      value :VI, 168
    end
  end
end

module Io
  LocalizedString = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.LocalizedString").msgclass
  LanguageCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.LanguageCode").enummodule
end
