# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/metrics.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/attributes_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/metrics.proto", :syntax => :proto3) do
    add_message "io.Metrics" do
      optional :created, :uint64, 1
      optional :appleWalletInstalls, :uint64, 2
      optional :googlePayInstalls, :uint64, 3
      optional :otherAndroidInstalls, :uint64, 4
      optional :appleWalletUninstalls, :uint64, 11
      optional :googlePayUninstalls, :uint64, 12
      optional :otherAndroidUninstalls, :uint64, 13
      optional :invalidations, :uint64, 20
    end
    add_message "io.UTM" do
      optional :source, :string, 1
      optional :medium, :string, 2
      optional :name, :string, 3
      optional :term, :string, 4
      optional :content, :string, 5
    end
    add_message "io.MetaLocation" do
      optional :country, :string, 1
      optional :city, :string, 2
      optional :state, :string, 3
      optional :latitude, :double, 4
      optional :longitude, :double, 5
    end
    add_message "io.Metadata" do
      optional :status, :enum, 1, "io.Status"
      repeated :lifecycleEvents, :enum, 2, "io.LifecycleEvents"
      optional :utm, :message, 3, "io.UTM"
      optional :altId, :string, 4
      optional :issueIpAddress, :string, 5
      optional :installIpAddress, :string, 6
      optional :renderLocation, :message, 7, "io.MetaLocation"
      optional :renderIpAddress, :string, 8
      optional :installUserAgent, :string, 9
      optional :renderUserAgent, :string, 10
      repeated :installDeviceAttributes, :enum, 11, "io.DeviceAttributes"
      repeated :renderDeviceAttributes, :enum, 12, "io.DeviceAttributes"
      optional :issueAt, :message, 13, "google.protobuf.Timestamp"
      optional :renderedAt, :message, 14, "google.protobuf.Timestamp"
      optional :firstInstalledAt, :message, 15, "google.protobuf.Timestamp"
      optional :lastInstalledAt, :message, 16, "google.protobuf.Timestamp"
      optional :firstUninstalledAt, :message, 17, "google.protobuf.Timestamp"
      optional :lastUninstalledAt, :message, 18, "google.protobuf.Timestamp"
      optional :invalidatedAt, :message, 19, "google.protobuf.Timestamp"
      optional :lastUpdatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_enum "io.LifecycleEvents" do
      value :NO_STATUS, 0
      value :RENDERED, 1
      value :INSTALLED_APPLE, 2
      value :INSTALLED_GOOGLE, 4
      value :INSTALLED_ANDROID_OTHER, 8
      value :UNINSTALLED_APPLE, 1024
      value :UNINSTALLED_GOOGLE, 2048
      value :UNINSTALLED_ANDROID_OTHER, 4096
      value :APPLE_PASS_CREATED, 8192
      value :GOOGLE_PAY_RECORD_CREATED, 16384
      value :INVALIDATE_REQUESTED, 262144
      value :INVALIDATE_CONFIRMED, 524288
    end
    add_enum "io.Status" do
      value :PASS_ISSUED, 0
      value :PASS_INSTALLED, 1
      value :PASS_UNINSTALLED, 2
      value :PASS_INVALIDATED, 3
    end
  end
end

module Io
  Metrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Metrics").msgclass
  UTM = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.UTM").msgclass
  MetaLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.MetaLocation").msgclass
  Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Metadata").msgclass
  LifecycleEvents = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.LifecycleEvents").enummodule
  Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Status").enummodule
end
