# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/pass.proto

require 'google/protobuf'

require 'io/image/image_pb'
require 'io/common/links_pb'
require 'io/common/metrics_pb'
require 'io/common/personal_pb'
require 'io/common/protocols_pb'
require 'io/common/proximity_pb'
require 'io/common/template_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/pass.proto", :syntax => :proto3) do
    add_message "io.PassOverrides" do
      optional :imageIds, :message, 1, "io.ImageIds"
      repeated :locations, :message, 3, "io.GPSLocation"
      repeated :beacons, :message, 4, "io.Beacon"
      repeated :links, :message, 5, "io.Link"
      optional :colors, :message, 6, "io.Colors"
    end
    add_message "io.PassOptions" do
      optional :apple, :message, 1, "io.AppleWalletSettings"
      optional :google, :message, 2, "io.GooglePaySettings"
    end
    add_message "io.Pass" do
      optional :id, :string, 1
      optional :classId, :string, 2
      optional :protocol, :enum, 3, "io.PassProtocol"
      optional :personDetails, :message, 4, "io.Person"
      optional :metadata, :message, 5, "io.Metadata"
      map :recordData, :string, :string, 6
      optional :externalId, :string, 7
    end
  end
end

module Io
  PassOverrides = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.PassOverrides").msgclass
  PassOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.PassOptions").msgclass
  Pass = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Pass").msgclass
end
