# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/personal.proto

require 'google/protobuf'

require 'io/common/common_objects_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/personal.proto", :syntax => :proto3) do
    add_message "io.Person" do
      optional :surname, :string, 1
      optional :forename, :string, 2
      repeated :otherNames, :string, 3
      optional :salutation, :string, 4
      optional :suffix, :string, 5
      optional :displayName, :string, 6
      optional :gender, :enum, 7, "io.Gender"
      optional :dateOfBirth, :message, 8, "io.Date"
      optional :emailAddress, :string, 9
      optional :mobileNumber, :string, 10
      optional :externalId, :string, 11
    end
    add_message "io.Address" do
      optional :addressLine1, :string, 1
      optional :addressLine2, :string, 2
      optional :addressLine3, :string, 3
      optional :city, :string, 4
      optional :state, :string, 5
      optional :zipCode, :string, 6
      optional :countryCode, :string, 7
    end
    add_enum "io.Gender" do
      value :NOT_KNOWN, 0
      value :MALE, 1
      value :FEMALE, 2
    end
  end
end

module Io
  Person = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Person").msgclass
  Address = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Address").msgclass
  Gender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Gender").enummodule
end
