# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/project.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/protocols_pb'
require 'io/common/template_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/project.proto", :syntax => :proto3) do
    add_message "io.Project" do
      optional :protocol, :enum, 1, "io.PassProtocol"
      optional :classId, :string, 2
      optional :name, :string, 3
      optional :shortCode, :string, 4
      optional :created, :message, 5, "google.protobuf.Timestamp"
      optional :secret, :string, 6
      optional :key, :string, 7
      optional :encryptedClassId, :string, 9
    end
    add_message "io.ProjectByShortCodeResult" do
      optional :project, :message, 1, "io.Project"
      optional :template, :message, 2, "io.PassTemplate"
    end
    add_message "io.ProjectStatusFilter" do
      optional :status, :enum, 1, "io.ProjectStatus"
    end
    add_enum "io.ProjectStatus" do
      value :NO_PROJECT_STATUS, 0
      value :PROJECT_ACTIVE_FOR_OBJECT_CREATION, 1
      value :PROJECT_DISABLED_FOR_OBJECT_CREATION, 2
      value :PROJECT_DRAFT, 4
      value :PROJECT_PUBLISHED, 8
      value :PROJECT_PRIVATE, 16
      value :PROJECT_OVER_QUOTA, 32
      value :PROJECT_DELETED, 64
    end
  end
end

module Io
  Project = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Project").msgclass
  ProjectByShortCodeResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.ProjectByShortCodeResult").msgclass
  ProjectStatusFilter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.ProjectStatusFilter").msgclass
  ProjectStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.ProjectStatus").enummodule
end
