# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/protocols.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/protocols.proto", :syntax => :proto3) do
    add_enum "io.PassProtocol" do
      value :PASS_PROTOCOL_DO_NOT_USE, 0
      value :RAW_PROTOCOL, 1
      value :V1_PROTOCOL, 2
      value :FLIGHT_PROTOCOL, 3
      value :MEMBERSHIP, 100
      value :SINGLE_USE_COUPON, 101
    end
    add_enum "io.ProtocolCommonEvents" do
      value :PROTOCOL_COMMON_EVENTS_DO_NOT_USE, 0
      value :EVENT_OBJECT_CREATED, 1
      value :EVENT_OBJECT_UPDATED, 2
      value :EVENT_OBJECT_EXPIRED, 3
      value :EVENT_OBJECT_DELETED, 4
      value :EVENT_PASS_ISSUED, 5
      value :EVENT_PASS_INSTALLED, 6
      value :EVENT_PASS_UNINSTALLED, 7
      value :EVENT_PASS_INVALIDATED, 8
    end
  end
end

module Io
  PassProtocol = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.PassProtocol").enummodule
  ProtocolCommonEvents = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.ProtocolCommonEvents").enummodule
end
