# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/proximity.proto

require 'google/protobuf'

require 'io/common/localization_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/proximity.proto", :syntax => :proto3) do
    add_message "io.Beacon" do
      optional :id, :string, 1
      optional :uuid, :string, 2
      optional :name, :string, 3
      optional :major, :uint32, 4
      optional :minor, :uint32, 5
      optional :lockScreenMessage, :string, 6
      optional :localizedLockScreenMessage, :message, 7, "io.LocalizedString"
      optional :position, :uint32, 8
    end
    add_message "io.GPSLocation" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :lat, :double, 3
      optional :lon, :double, 4
      optional :alt, :int32, 5
      optional :lockScreenMessage, :string, 6
      optional :localizedLockScreenMessage, :message, 7, "io.LocalizedString"
      optional :position, :uint32, 8
    end
    add_message "io.RelevantDate" do
      optional :timestamp, :uint32, 1
    end
  end
end

module Io
  Beacon = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Beacon").msgclass
  GPSLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.GPSLocation").msgclass
  RelevantDate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.RelevantDate").msgclass
end
