# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/template.proto

require 'google/protobuf'

require 'io/common/common_objects_pb'
require 'io/common/localization_pb'
require 'io/common/protocols_pb'
require 'io/common/proximity_pb'
require 'io/common/links_pb'
require 'io/common/tracking_pb'
require 'io/image/image_pb'
require 'google/protobuf/timestamp_pb'
require 'io/common/expiry_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/template.proto", :syntax => :proto3) do
    add_message "io.SelectOption" do
      optional :listPriority, :uint32, 1
      optional :textLabel, :string, 2
      optional :localizedTextLabel, :message, 3, "io.LocalizedString"
      optional :value, :string, 4
    end
    add_message "io.Barcode" do
      optional :payload, :string, 1
      optional :format, :enum, 2, "io.BarcodeType"
      optional :altText, :string, 3
      optional :localizedAltText, :message, 4, "io.LocalizedString"
      optional :messageEncoding, :string, 5
    end
    add_message "io.PassTemplate" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :protocol, :enum, 3, "io.PassProtocol"
      optional :revision, :uint32, 4
      optional :defaultLanguage, :enum, 5, "io.LanguageCode"
      optional :organizationName, :string, 6
      optional :localizedOrganizationName, :message, 7, "io.LocalizedString"
      optional :description, :string, 8
      optional :localizedDescription, :message, 9, "io.LocalizedString"
      optional :data, :message, 10, "io.Data"
      optional :colors, :message, 13, "io.Colors"
      optional :barcode, :message, 14, "io.Barcode"
      optional :nfcEnabled, :message, 15, "io.NFC"
      optional :sharing, :message, 16, "io.Sharing"
      optional :appleWalletSettings, :message, 17, "io.AppleWalletSettings"
      optional :googlePaySettings, :message, 18, "io.GooglePaySettings"
      repeated :locations, :message, 19, "io.GPSLocation"
      repeated :beacons, :message, 20, "io.Beacon"
      repeated :links, :message, 21, "io.Link"
      optional :timezone, :string, 22
      optional :expirySettings, :message, 23, "io.ExpirySettings"
      oneof :ImageAssets do
        optional :imageIds, :message, 11, "io.ImageIds"
        optional :images, :message, 12, "io.ImageData"
      end
    end
    add_message "io.AppleWalletSettings" do
      optional :passType, :enum, 1, "io.ApplePassType"
      optional :userInfo, :string, 2
      optional :appLaunchUrl, :string, 3
      repeated :associatedStoreIdentifiers, :uint32, 4
      optional :maxDistance, :uint32, 5
      repeated :appStoreCountries, :string, 6
      optional :transitType, :enum, 7, "io.TransitType"
      optional :groupingIdentifier, :string, 8
    end
    add_message "io.GooglePaySettings" do
      optional :passType, :enum, 1, "io.GooglePayPassType"
      optional :androidApp, :message, 2, "io.GooglePayApp"
      optional :iosApp, :message, 3, "io.GooglePayApp"
      optional :webApp, :message, 4, "io.GooglePayApp"
      optional :classTemplateInfo, :string, 5
      optional :backgroundColor, :string, 6
    end
    add_message "io.GooglePayApp" do
      optional :url, :message, 1, "io.Url"
      optional :title, :string, 2
      optional :localizedTitle, :message, 3, "io.LocalizedString"
      optional :description, :string, 4
      optional :localizedDescription, :message, 5, "io.LocalizedString"
    end
    add_message "io.Data" do
      repeated :dataFields, :message, 1, "io.DataField"
      optional :dataCollectionPageSettings, :message, 2, "io.DataCollectionPageSettings"
    end
    add_message "io.DataCollectionPageSettings" do
      optional :title, :string, 1
      optional :localizedTitle, :message, 2, "io.LocalizedString"
      optional :description, :string, 3
      optional :localizedDescription, :message, 4, "io.LocalizedString"
      optional :submitButtonText, :string, 5
      optional :localizedSubmitButtonText, :message, 6, "io.LocalizedString"
      optional :loadingText, :string, 7
      optional :localizedLoadingText, :message, 8, "io.LocalizedString"
      optional :thankYouText, :string, 9
      optional :localizedThankYouText, :message, 10, "io.LocalizedString"
      optional :pageBackgroundColor, :string, 11
      optional :localizedPageBackgroundColor, :message, 12, "io.LocalizedString"
      optional :trackingSettings, :message, 13, "io.TrackingSettings"
      optional :submitButtonTextColor, :string, 14
      optional :submitButtonBackgroundColor, :string, 15
      optional :footerText, :string, 16
      optional :localizedFooterText, :message, 17, "io.LocalizedString"
      optional :cssOverrides, :string, 18
    end
    add_message "io.PassTemplateResponse" do
      optional :template, :message, 1, "io.PassTemplate"
      optional :Name, :string, 2
      optional :ownerUsername, :string, 3
      optional :protocol, :enum, 4, "io.PassProtocol"
      optional :revision, :uint32, 5
      optional :createdAt, :message, 6, "google.protobuf.Timestamp"
      optional :updatedAt, :message, 7, "google.protobuf.Timestamp"
    end
    add_message "io.Colors" do
      optional :backgroundColor, :string, 1
      optional :labelColor, :string, 2
      optional :textColor, :string, 3
      optional :stripColor, :string, 4
    end
    add_message "io.CopyObjectInput" do
      optional :id, :string, 1
      optional :newName, :string, 2
    end
    add_message "io.NFC" do
      optional :enabled, :bool, 1
      optional :certificateId, :string, 2
      optional :payload, :string, 3
    end
    add_message "io.DataField" do
      optional :uniqueName, :string, 1
      optional :templateId, :string, 2
      optional :fieldType, :enum, 3, "io.FieldType"
      optional :isRequired, :bool, 4
      optional :label, :string, 5
      optional :localizedLabel, :message, 6, "io.LocalizedString"
      optional :dataType, :enum, 7, "io.DataType"
      optional :defaultValue, :string, 8
      optional :localizedDefaultValue, :message, 9, "io.LocalizedString"
      optional :validation, :string, 10
      optional :userCanSetValue, :bool, 11
      optional :currencyCode, :string, 12
      optional :appleWalletFieldRenderOptions, :message, 13, "io.AppleWalletFieldRenderOptions"
      optional :dataCollectionFieldRenderOptions, :message, 14, "io.DataCollectionFieldRenderOptions"
      repeated :usage, :enum, 15, "io.UsageType"
      optional :googlePayFieldRenderOptions, :message, 16, "io.GooglePayFieldRenderOptions"
      optional :defaultTelCountryCode, :string, 17
    end
    add_message "io.AppleWalletFieldRenderOptions" do
      optional :textAlignment, :enum, 2, "io.TextAlignment"
      optional :positionSettings, :message, 3, "io.PositionSettings"
      optional :changeMessage, :string, 4
      optional :localizedChangeMessage, :message, 5, "io.LocalizedString"
      optional :dateStyle, :enum, 6, "io.DateTimeStyle"
      optional :timeStyle, :enum, 7, "io.DateTimeStyle"
      optional :numberStyle, :enum, 8, "io.NumberStyle"
      repeated :suppressLinkDetection, :enum, 9, "io.LinkDetector"
      optional :ignoreTimezone, :bool, 10
      optional :isRelativeDate, :bool, 11
    end
    add_message "io.GooglePayFieldRenderOptions" do
      optional :googlePayPosition, :enum, 1, "io.GooglePayField"
      optional :textModulePriority, :uint32, 2
    end
    add_message "io.PositionSettings" do
      optional :section, :enum, 1, "io.FieldSection"
      optional :priority, :uint32, 2
    end
    add_message "io.DataCollectionFieldRenderOptions" do
      optional :helpText, :string, 1
      optional :localizedHelpText, :message, 2, "io.LocalizedString"
      optional :displayOrder, :int32, 3
      optional :placeholder, :string, 5
      repeated :selectOptions, :message, 6, "io.SelectOption"
      optional :localizedPlaceholder, :message, 7, "io.LocalizedString"
      optional :autocomplete, :bool, 8
      optional :addressRenderOptions, :message, 9, "io.AddressRenderOptions"
      optional :localizedYearPlaceholder, :string, 10
      optional :localizedMonthPlaceholder, :string, 11
      optional :localizedDayPlaceholder, :string, 12
    end
    add_message "io.AddressRenderOptions" do
      optional :address1Label, :string, 1
      optional :address2Label, :string, 2
      optional :cityLabel, :string, 3
      optional :countryLabel, :string, 4
      optional :zipLabel, :string, 5
      optional :address1Placeholder, :string, 6
      optional :address2Placeholder, :string, 7
      optional :cityPlaceholder, :string, 8
      optional :countryPlaceholder, :string, 9
      optional :zipPlaceholder, :string, 10
      optional :localizedAddress1Label, :message, 11, "io.LocalizedString"
      optional :localizedAddress2Label, :message, 12, "io.LocalizedString"
      optional :localizedCityLabel, :message, 13, "io.LocalizedString"
      optional :localizedCountryLabel, :message, 14, "io.LocalizedString"
      optional :localizedZipLabel, :message, 15, "io.LocalizedString"
      optional :localizedAddress1Placeholder, :message, 16, "io.LocalizedString"
      optional :localizedAddress2Placeholder, :message, 17, "io.LocalizedString"
      optional :localizedCityPlaceholder, :message, 18, "io.LocalizedString"
      optional :localizedCountryPlaceholder, :message, 19, "io.LocalizedString"
      optional :localizedZipPlaceholder, :message, 20, "io.LocalizedString"
    end
    add_message "io.Sharing" do
      optional :prohibitSharing, :bool, 1
      optional :url, :string, 2
      optional :description, :string, 3
      optional :localizedDescription, :message, 4, "io.LocalizedString"
    end
    add_message "io.DefaultTemplateRequest" do
      optional :protocol, :enum, 1, "io.PassProtocol"
      optional :revision, :uint32, 2
    end
    add_enum "io.ApplePassType" do
      value :APPLE_NOT_SUPPORTED, 0
      value :BOARDING_PASS, 1
      value :COUPON, 2
      value :EVENT_TICKET, 3
      value :GENERIC, 4
      value :STORE_CARD, 5
    end
    add_enum "io.GooglePayPassType" do
      value :GOOGLE_PAY_NOT_SUPPORTED, 0
      value :EVENT, 1
      value :FLIGHT, 2
      value :GIFT, 3
      value :LOYALTY, 4
      value :OFFER, 5
      value :TRANSIT, 6
    end
    add_enum "io.BarcodeType" do
      value :BARCODE_TYPE_DO_NOT_USE, 0
      value :QR, 1
      value :AZTEC, 2
      value :PDF417, 3
      value :CODE128, 4
      value :NONE, 5
    end
    add_enum "io.FieldType" do
      value :FIELD_TYPE_NONE, 0
      value :META, 1
      value :PII, 2
      value :UNIVERSAL_FIELDS, 3
      value :PROTOCOL_FIELDS, 4
      value :CUSTOM_FIELDS, 5
    end
    add_enum "io.StandardFields" do
      value :STANDARD_FIELDS_DO_NOT_USE, 0
      value :STANDARD_MESSAGES, 1
      value :STANDARD_LEGAL, 2
      value :STANDARD_EXPIRY_DATE, 3
      value :STANDARD_USEFUL_LINKS, 4
      value :STANDARD_OPT_OUT, 5
      value :STANDARD_LOCATIONS, 6
    end
    add_enum "io.TextAlignment" do
      value :TEXT_ALIGNMENT_DO_NOT_USE, 0
      value :LEFT, 1
      value :CENTER, 2
      value :RIGHT, 3
      value :NATURAL, 4
    end
    add_enum "io.DateTimeStyle" do
      value :DATE_TIME_STYLE_DO_NOT_USE, 0
      value :DATE_TIME_STYLE_SHORT, 1
      value :DATE_TIME_STYLE_MEDIUM, 2
      value :DATE_TIME_STYLE_LONG, 3
      value :DATE_TIME_STYLE_FULL, 4
    end
    add_enum "io.LinkDetector" do
      value :LINK_DETECTOR_DO_NOT_USE, 0
      value :LINK_DETECTOR_ADDRESS, 1
      value :LINK_DETECTOR_DATE, 2
      value :LINK_DETECTOR_URL, 3
      value :LINK_DETECTOR_PHONE, 4
    end
    add_enum "io.NumberStyle" do
      value :NUMBER_STYLE_DO_NOT_USE, 0
      value :NUMBER_STYLE_DECIMAL, 1
      value :NUMBER_STYLE_PERCENT, 2
      value :NUMBER_STYLE_SCIENTIFIC, 3
      value :NUMBER_STYLE_SPELL, 4
    end
    add_enum "io.TransitType" do
      value :TRANSIT_TYPE_DO_NOT_USE, 0
      value :TRANSIT_TYPE_AIR, 1
      value :TRANSIT_TYPE_BOAT, 2
      value :TRANSIT_TYPE_BUS, 3
      value :TRANSIT_TYPE_GENERIC, 4
      value :TRANSIT_TYPE_TRAIN, 5
      value :TRANSIT_TYPE_TRAM, 6
    end
    add_enum "io.DataType" do
      value :DATA_TYPE_NONE, 0
      value :TEXT, 1
      value :TEXT_LONG, 2
      value :DATE_YYYYMMDD, 3
      value :DATE_YYYYMM, 4
      value :DATE_MMDD, 5
      value :TIME, 6
      value :DATE_TIME, 7
      value :INT, 8
      value :NUMBER, 9
      value :EMAIL, 10
      value :URL, 11
      value :TEL, 12
      value :ADDRESS, 13
      value :IMAGE, 15
      value :CURRENCY, 16
      value :BOOLEAN, 17
      value :OPTIONS, 18
      value :DATE_MM, 19
    end
    add_enum "io.DataStyle" do
      value :NO_STYLE, 0
      value :DATE_SHORT, 1
      value :DATE_MEDIUM, 2
      value :DATE_LONG, 3
      value :DATE_FULL, 4
      value :TIME_SHORT, 5
      value :TIME_MEDIUM, 6
      value :TIME_LONG, 7
      value :TIME_FULL, 8
      value :DATE_TIME_SHORT, 9
      value :DATE_TIME_MEDIUM, 10
      value :DATE_TIME_LONG, 11
      value :DATE_TIME_FULL, 12
      value :NUMBER_DECIMAL, 13
    end
    add_enum "io.FieldSection" do
      value :FIELD_SECTION_DO_NOT_USE, 0
      value :BACK_FIELDS, 1
      value :PRIMARY_FIELDS, 2
      value :SECONDARY_FIELDS, 3
      value :AUXILIARY_FIELDS, 4
      value :HEADER_FIELDS, 5
    end
    add_enum "io.GooglePayField" do
      value :GOOGLE_PAY_FIELD_DO_NOT_USE, 0
      value :GOOGLE_PAY_BOARDING_AIRLINE_NAME, 1
      value :GOOGLE_PAY_BOARDING_AIRLINE_CODE, 2
      value :GOOGLE_PAY_BOARDING_ORIGIN, 3
      value :GOOGLE_PAY_BOARDING_DESTINATION, 4
      value :GOOGLE_PAY_BOARDING_ORIGIN_TERMINAL, 5
      value :GOOGLE_PAY_BOARDING_ORIGIN_GATE, 6
      value :GOOGLE_PAY_BOARDING_BOARDING_TIME, 7
      value :GOOGLE_PAY_BOARDING_PASSENGER_NAME, 8
      value :GOOGLE_PAY_BOARDING_ZONE_GROUP, 9
      value :GOOGLE_PAY_BOARDING_SEAT, 10
      value :GOOGLE_PAY_BOARDING_BOARDING_POSITION, 11
      value :GOOGLE_PAY_BOARDING_BOARDING_SEQUENCE, 12
      value :GOOGLE_PAY_BOARDING_BOARDING_DOOR, 13
      value :GOOGLE_PAY_BOARDING_FLIGHT_NUMBER, 14
      value :GOOGLE_PAY_BOARDING_CONFIRMATION_NUMBER, 15
      value :GOOGLE_PAY_BOARDING_TICKET_NUMBER, 16
      value :GOOGLE_PAY_BOARDING_FREQUENT_FLYER_NUMBER, 17
      value :GOOGLE_PAY_BOARDING_GATE_CLOSES, 18
      value :GOOGLE_PAY_BOARDING_DEPARTURE_TIME, 19
      value :GOOGLE_PAY_BOARDING_ARRIVAL_TIME, 20
      value :GOOGLE_PAY_BOARDING_ARRIVAL_TERMINAL, 21
      value :GOOGLE_PAY_BOARDING_ARRIVAL_GATE, 22
      value :GOOGLE_PAY_EVENT_NAME, 100
      value :GOOGLE_PAY_EVENT_VENUE_NAME, 101
      value :GOOGLE_PAY_EVENT_VENUE_ADDRESS, 102
      value :GOOGLE_PAY_EVENT_GATE, 103
      value :GOOGLE_PAY_EVENT_SECTION, 104
      value :GOOGLE_PAY_EVENT_ROW, 105
      value :GOOGLE_PAY_EVENT_SEAT, 106
      value :GOOGLE_PAY_EVENT_TICKET_HOLDER, 107
      value :GOOGLE_PAY_EVENT_DOORS_OPEN, 108
      value :GOOGLE_PAY_EVENT_START, 109
      value :GOOGLE_PAY_EVENT_END, 110
      value :GOOGLE_PAY_EVENT_TICKET_TYPE, 111
      value :GOOGLE_PAY_EVENT_TICKET_NUMBER, 112
      value :GOOGLE_PAY_EVENT_CONFIRMATION_NUMBER, 113
      value :GOOGLE_PAY_EVENT_FACE_VALUE, 114
      value :GOOGLE_PAY_EVENT_FINE_PRINT, 115
      value :GOOGLE_PAY_GIFT_MERCHANT_NAME, 200
      value :GOOGLE_PAY_GIFT_BALANCE, 201
      value :GOOGLE_PAY_GIFT_CARD_NUMBER, 202
      value :GOOGLE_PAY_GIFT_BALANCE_UPDATE_TIME, 203
      value :GOOGLE_PAY_GIFT_PIN, 204
      value :GOOGLE_PAY_GIFT_EVENT_NUMBER, 205
      value :GOOGLE_PAY_LOYALTY_PROGRAM_NAME, 300
      value :GOOGLE_PAY_LOYALTY_POINTS, 301
      value :GOOGLE_PAY_LOYALTY_SECONDARY_POINTS, 302
      value :GOOGLE_PAY_LOYALTY_ACCOUNT_NAME, 303
      value :GOOGLE_PAY_LOYALTY_ACCOUNT_ID, 304
      value :GOOGLE_PAY_LOYALTY_REWARDS_TIER, 305
      value :GOOGLE_PAY_LOYALTY_SECONDARY_REWARDS_TIER, 306
      value :GOOGLE_PAY_OFFER_TITLE, 400
      value :GOOGLE_PAY_OFFER_PROVIDER, 401
      value :GOOGLE_PAY_OFFER_DETAILS, 402
      value :GOOGLE_PAY_OFFER_FINE_PRINT, 403
      value :GOOGLE_PAY_OFFER_SHORT_TITLE, 404
      value :GOOGLE_PAY_TRANSIT_ISSUER_NAME, 500
      value :GOOGLE_PAY_TRANSIT_DEPARTURE, 501
      value :GOOGLE_PAY_TRANSIT_DEPARTURE_TIME, 502
      value :GOOGLE_PAY_TRANSIT_VALID_FROM, 503
      value :GOOGLE_PAY_TRANSIT_VALID_UNTIL, 504
      value :GOOGLE_PAY_TRANSIT_ARRIVAL, 505
      value :GOOGLE_PAY_TRANSIT_PASSENGER_NAMES, 506
      value :GOOGLE_PAY_TRANSIT_CARRIAGE, 507
      value :GOOGLE_PAY_TRANSIT_COACH, 508
      value :GOOGLE_PAY_TRANSIT_SEAT, 509
      value :GOOGLE_PAY_TRANSIT_TICKET_NUMBER, 510
      value :GOOGLE_PAY_TRANSIT_TICKET_STATUS, 511
      value :GOOGLE_PAY_TRANSIT_FARE_NAME, 512
      value :GOOGLE_PAY_TRANSIT_PLATFORM, 513
      value :GOOGLE_PAY_TRANSIT_ZONE, 514
      value :GOOGLE_PAY_TRANSIT_FARE_CLASS, 515
      value :GOOGLE_PAY_TRANSIT_CONCESSION_CATEGORY, 516
      value :GOOGLE_PAY_TRANSIT_ROUTE_RESTRICTIONS, 517
      value :GOOGLE_PAY_TRANSIT_ROUTE_RESTRICTION_DETAILS, 518
      value :GOOGLE_PAY_TRANSIT_TIME_RESTRICTIONS, 519
      value :GOOGLE_PAY_TRANSIT_OTHER_RESTRICTIONS, 520
      value :GOOGLE_PAY_TRANSIT_RECEIPT_NUMBER, 521
      value :GOOGLE_PAY_TRANSIT_PURCHASE_DATE, 522
      value :GOOGLE_PAY_TRANSIT_ACCOUNT_ID, 523
      value :GOOGLE_PAY_TRANSIT_CONFIRMATION_CODE, 524
      value :GOOGLE_PAY_TRANSIT_FACE_VALUE, 525
      value :GOOGLE_PAY_TRANSIT_PURCHASE_PRICE, 526
      value :GOOGLE_PAY_TRANSIT_DISCOUNT_MESSAGE, 527
      value :GOOGLE_PAY_TEXT_MODULE, 1000
      value :GOOGLE_PAY_ISSUER_NAME, 1001
      value :GOOGLE_PAY_STATIC_TEXT_MODULE, 1002
    end
  end
end

module Io
  SelectOption = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.SelectOption").msgclass
  Barcode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Barcode").msgclass
  PassTemplate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.PassTemplate").msgclass
  AppleWalletSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.AppleWalletSettings").msgclass
  GooglePaySettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.GooglePaySettings").msgclass
  GooglePayApp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.GooglePayApp").msgclass
  Data = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Data").msgclass
  DataCollectionPageSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DataCollectionPageSettings").msgclass
  PassTemplateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.PassTemplateResponse").msgclass
  Colors = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Colors").msgclass
  CopyObjectInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.CopyObjectInput").msgclass
  NFC = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.NFC").msgclass
  DataField = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DataField").msgclass
  AppleWalletFieldRenderOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.AppleWalletFieldRenderOptions").msgclass
  GooglePayFieldRenderOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.GooglePayFieldRenderOptions").msgclass
  PositionSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.PositionSettings").msgclass
  DataCollectionFieldRenderOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DataCollectionFieldRenderOptions").msgclass
  AddressRenderOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.AddressRenderOptions").msgclass
  Sharing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Sharing").msgclass
  DefaultTemplateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DefaultTemplateRequest").msgclass
  ApplePassType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.ApplePassType").enummodule
  GooglePayPassType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.GooglePayPassType").enummodule
  BarcodeType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.BarcodeType").enummodule
  FieldType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.FieldType").enummodule
  StandardFields = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.StandardFields").enummodule
  TextAlignment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.TextAlignment").enummodule
  DateTimeStyle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DateTimeStyle").enummodule
  LinkDetector = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.LinkDetector").enummodule
  NumberStyle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.NumberStyle").enummodule
  TransitType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.TransitType").enummodule
  DataType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DataType").enummodule
  DataStyle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DataStyle").enummodule
  FieldSection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.FieldSection").enummodule
  GooglePayField = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.GooglePayField").enummodule
end
