# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/tracking.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/tracking.proto", :syntax => :proto3) do
    add_message "io.FacebookPixelSettings" do
      optional :pixelId, :string, 1
      repeated :dataCollectionPageStandardEvents, :message, 2, "io.StandardEvent"
      repeated :dataCollectionPageCustomEvents, :message, 3, "io.CustomEvent"
      repeated :passPageStandardEvents, :message, 4, "io.StandardEvent"
      repeated :passPageCustomEvents, :message, 5, "io.CustomEvent"
      repeated :customerInitiatedRedemptionPageStandardEvents, :message, 6, "io.StandardEvent"
      repeated :customerInitiatedRedemptionPageCustomEvents, :message, 7, "io.CustomEvent"
    end
    add_message "io.StandardEvent" do
      optional :event, :enum, 1, "io.FbPixelStandardEvent"
      optional :properties, :string, 3
    end
    add_message "io.CustomEvent" do
      optional :event, :string, 1
      optional :properties, :string, 3
    end
    add_message "io.GoogleAnalyticsSettings" do
      repeated :trackingIds, :string, 1
      repeated :dataCollectionPageEvents, :enum, 2, "io.GoogleAnalyticsDataCollectionPageEvent"
      repeated :passRenderPageEvents, :enum, 3, "io.GoogleAnalyticsPassRenderPageEvent"
      repeated :customerInitiatedRedemption, :enum, 4, "io.GoogleAnalyticsCustomerInitiatedRedemptionPageEvent"
    end
    add_message "io.TrackingSettings" do
      optional :facebookPixelSettings, :message, 1, "io.FacebookPixelSettings"
      optional :googleAnalyticsSettings, :message, 2, "io.GoogleAnalyticsSettings"
    end
    add_enum "io.FbPixelStandardEvent" do
      value :FBP_STANDARD_EVENT_DO_NOT_USE, 0
      value :FBP_STANDARD_EVENT_PAGE_VIEW, 1
      value :FBP_STANDARD_EVENT_COMPLETE_REGISTRATION, 2
      value :FBP_STANDARD_EVENT_LEAD, 3
      value :FBP_STANDARD_EVENT_PURCHASE, 4
      value :FBP_STANDARD_EVENT_SCHEDULE, 5
      value :FBP_STANDARD_EVENT_START_TRIAL, 6
      value :FBP_STANDARD_EVENT_SUBMIT_APPLICATION, 7
      value :FBP_STANDARD_EVENT_SUBSCRIBE, 8
      value :FBP_STANDARD_EVENT_VIEW_CONTENT, 9
    end
    add_enum "io.GoogleAnalyticsDataCollectionPageEvent" do
      value :GA_DC_EVENT_DO_NOT_USE, 0
      value :GA_DC_EVENT_PAGE_VIEW, 1
      value :GA_DC_EVENT_SUBMIT_FORM, 2
    end
    add_enum "io.GoogleAnalyticsPassRenderPageEvent" do
      value :GA_PP_EVENT_DO_NOT_USE, 0
      value :GA_PP_EVENT_PAGE_VIEW, 1
      value :GA_PP_EVENT_ADD_TO_APPLE_WALLET_CLICK, 2
      value :GA_PP_EVENT_VIEW_PASS_IN_APPLE_WALLET_CLICK, 3
      value :GA_PP_EVENT_SAVE_TO_GOOGLE_PAY_CLICK, 4
      value :GA_PP_EVENT_CHANGE_LANGUAGE, 5
    end
    add_enum "io.GoogleAnalyticsCustomerInitiatedRedemptionPageEvent" do
      value :GA_CIRP_EVENT_DO_NOT_USE, 0
      value :GA_CIRP_EVENT_PAGE_VIEW, 1
      value :GA_CIRP_EVENT_REDEEM, 2
    end
  end
end

module Io
  FacebookPixelSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.FacebookPixelSettings").msgclass
  StandardEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.StandardEvent").msgclass
  CustomEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.CustomEvent").msgclass
  GoogleAnalyticsSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.GoogleAnalyticsSettings").msgclass
  TrackingSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.TrackingSettings").msgclass
  FbPixelStandardEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.FbPixelStandardEvent").enummodule
  GoogleAnalyticsDataCollectionPageEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.GoogleAnalyticsDataCollectionPageEvent").enummodule
  GoogleAnalyticsPassRenderPageEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.GoogleAnalyticsPassRenderPageEvent").enummodule
  GoogleAnalyticsCustomerInitiatedRedemptionPageEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.GoogleAnalyticsCustomerInitiatedRedemptionPageEvent").enummodule
end
