# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/transaction.proto

require 'google/protobuf'

require 'io/common/common_objects_pb'
require 'io/common/proximity_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/transaction.proto", :syntax => :proto3) do
    add_message "io.Transaction" do
      optional :referenceId, :string, 1
      optional :totalPrice, :float, 2
      repeated :orderItems, :message, 3, "io.OrderItem"
      optional :discount, :float, 4
      repeated :discountItems, :message, 5, "io.DiscountItem"
      optional :serviceCharge, :float, 6
      optional :totalTax, :float, 7
      optional :finalPrice, :float, 8
      optional :roundingDifference, :float, 9
      optional :isRefunded, :bool, 10
      optional :timestamp, :message, 11, "io.Date"
      optional :currency, :string, 12
      optional :location, :message, 13, "io.GPSLocation"
      optional :transactionSource, :string, 14
    end
    add_message "io.DiscountItem" do
      optional :discountCode, :string, 1
      optional :voucherCode, :string, 2
      optional :amount, :float, 4
      optional :itemName, :string, 5
    end
    add_message "io.OrderItem" do
      optional :amount, :float, 1
      optional :tax, :float, 2
      optional :itemName, :string, 3
      optional :quantity, :int32, 4
      optional :sku, :string, 5
    end
  end
end

module Io
  Transaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Transaction").msgclass
  DiscountItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DiscountItem").msgclass
  OrderItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.OrderItem").msgclass
end
