# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/useragent.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/common/useragent.proto", :syntax => :proto3) do
    add_message "io.UserAgent" do
      optional :raw, :string, 1
      optional :platform, :string, 2
      optional :os, :string, 3
      optional :osVersion, :string, 4
      optional :engine, :string, 5
      optional :engineVersion, :string, 6
      optional :browser, :string, 7
      optional :browserVersion, :string, 8
      optional :localization, :string, 9
      optional :mobile, :bool, 10
      optional :walletCompatible, :bool, 11
    end
  end
end

module Io
  UserAgent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.UserAgent").msgclass
end
