# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/single_use_coupons/campaign.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/localization_pb'
require 'io/common/project_pb'
require 'io/common/reporting_pb'


descriptor_data = "\n$io/single_use_coupons/campaign.proto\x12\x12single_use_coupons\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cio/common/localization.proto\x1a\x17io/common/project.proto\x1a\x19io/common/reporting.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xac\x03\n\x0e\x43ouponCampaign\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12*\n\rlocalizedName\x18\x03 \x01(\x0b\x32\x13.io.LocalizedString\x12!\n\x06status\x18\x05 \x03(\x0e\x32\x11.io.ProjectStatus\x12\x1a\n\x12passTypeIdentifier\x18\x06 \x01(\t\x12\x14\n\x0cianaTimezone\x18\x07 \x01(\t\x12+\n\x07\x63reated\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp:\x92\x01\x92\x41\x8e\x01\n\x8b\x01*\x0f\x43oupon Campaign2HHolds the business logic & distribution settings of the Coupon Campaign.\xd2\x01\x04name\xd2\x01\x07offerId\xd2\x01\x06status\xd2\x01\tstartDate\xd2\x01\x07\x65ndDateJ\x04\x08\x04\x10\x05J\x04\x08\x08\x10\tJ\x04\x08\t\x10\n\"\x9b\x02\n\x1f\x43ouponCampaignAnalyticsResponse\x12\x1a\n\x06period\x18\x01 \x01(\x0e\x32\n.io.Period\x12\x10\n\x08redeemed\x18\x02 \x01(\r\x12$\n\x07\x64\x65vices\x18\x03 \x01(\x0b\x32\x13.io.DeviceBreakdown\x12Q\n\x07sources\x18\x04 \x03(\x0b\x32@.single_use_coupons.CouponCampaignAnalyticsResponse.SourcesEntry\x12!\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32\x13.io.ChartDataPoints\x1a.\n\x0cSourcesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"n\n\x13\x43\x61mpaignCopyRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12!\n\x06status\x18\x03 \x03(\x0e\x32\x11.io.ProjectStatus\x12\x1a\n\x12passTypeIdentifier\x18\x04 \x01(\tB|\n!com.passkit.grpc.SingleUseCouponsZ7stash.passkit.com/io/model/sdk/go/io/single_use_coupons\xaa\x02\x1dPassKit.Grpc.SingleUseCouponsb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module SingleUseCoupons
  CouponCampaign = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.CouponCampaign").msgclass
  CouponCampaignAnalyticsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.CouponCampaignAnalyticsResponse").msgclass
  CampaignCopyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.CampaignCopyRequest").msgclass
end
