# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/raw/pass.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/metrics_pb'
require 'io/common/filter_pb'
require 'io/common/pass_pb'
require 'io/common/personal_pb'


descriptor_data = "\n\x11io/raw/pass.proto\x12\x03raw\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17io/common/metrics.proto\x1a\x16io/common/filter.proto\x1a\x14io/common/pass.proto\x1a\x18io/common/personal.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xc7\x05\n\x04Pass\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nexternalId\x18\x02 \x01(\t\x12\x15\n\rpassProjectId\x18\x03 \x01(\t\x12\x16\n\x0epassTemplateId\x18\x04 \x01(\t\x12#\n\x0fpersonalDetails\x18\x05 \x01(\x0b\x32\n.io.Person\x12/\n\x0b\x64ynamicData\x18\x06 \x03(\x0b\x32\x1a.raw.Pass.DynamicDataEntry\x12\x0e\n\x06optOut\x18\x08 \x01(\x08\x12\x10\n\x08isVoided\x18\t \x01(\x08\x12\x32\n\x0einvalidateDate\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nexpiryDate\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12$\n\x0bpassOptions\x18\x0c \x01(\x0b\x32\x0f.io.PassOptions\x12(\n\rpassOverrides\x18\r \x01(\x0b\x32\x11.io.PassOverrides\x12\"\n\x0cpassMetaData\x18\x0e \x01(\x0b\x32\x0c.io.Metadata\x12+\n\x07\x63reated\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x10 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a\x32\n\x10\x44ynamicDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01:\x91\x01\x92\x41\x8d\x01\n\x8a\x01*\x04Pass2aPass contains dynamic information that combined with a Pass Project & Template results in a pass.\xd2\x01\rpassProjectId\xd2\x01\x0epassTemplateId\"J\n\x1dPassRecordByExternalIdRequest\x12\x15\n\rpassProjectId\x18\x01 \x01(\t\x12\x12\n\nexternalId\x18\x02 \x01(\t\"U\n\x1eListPassesByPassProjectRequest\x12\x15\n\rpassProjectId\x18\x01 \x01(\t\x12\x1c\n\x07\x66ilters\x18\x02 \x01(\x0b\x32\x0b.io.Filters\"V\n\x1fListPassesByPassTemplateRequest\x12\x15\n\rpassProjectId\x18\x01 \x01(\t\x12\x1c\n\x07\x66ilters\x18\x02 \x01(\x0b\x32\x0b.io.FiltersBS\n\x14\x63om.passkit.grpc.RawZ(stash.passkit.com/io/model/sdk/go/io/raw\xaa\x02\x10PassKit.Grpc.Rawb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Raw
  Pass = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("raw.Pass").msgclass
  PassRecordByExternalIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("raw.PassRecordByExternalIdRequest").msgclass
  ListPassesByPassProjectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("raw.ListPassesByPassProjectRequest").msgclass
  ListPassesByPassTemplateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("raw.ListPassesByPassTemplateRequest").msgclass
end
