# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/user/user.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/personal_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/user/user.proto", :syntax => :proto3) do
    add_message "io.NewUserResponse" do
      optional :userId, :string, 1
      optional :companyId, :string, 2
      optional :username, :string, 3
      optional :emailAddress, :string, 4
      optional :secret, :string, 5
      optional :certificate, :string, 6
      optional :privateKey, :string, 7
    end
    add_message "io.NewUser" do
      optional :username, :string, 1
      optional :password, :string, 2
      optional :emailAddress, :string, 3
      optional :sendEmail, :bool, 4
      optional :companyName, :string, 5
      optional :mobileNumber, :string, 6
      optional :twoFactorAuth, :bool, 7
      optional :isOwner, :bool, 8
      optional :readOnly, :bool, 9
    end
    add_message "io.GetUserResponse" do
      optional :email, :string, 1
      optional :username, :string, 2
      optional :companyId, :string, 3
      optional :companyName, :string, 4
      optional :companyStatus, :uint64, 5
      optional :createdAt, :message, 6, "google.protobuf.Timestamp"
    end
    add_message "io.BillingMeta" do
      optional :companyName, :string, 1
      optional :taxId, :string, 2
      optional :reference, :string, 3
      optional :billingAddress, :message, 4, "io.Address"
    end
    add_message "io.Credentials" do
      optional :username, :string, 1
      optional :password, :string, 2
    end
    add_message "io.JWT" do
      optional :token, :string, 1
    end
    add_message "io.PasswordResetInput" do
      optional :id, :string, 1
      optional :registeredEmail, :string, 2
      optional :newPassword, :string, 3
      optional :confirmNewPassword, :string, 4
    end
    add_message "io.Username" do
      optional :username, :string, 1
    end
  end
end

module Io
  NewUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.NewUserResponse").msgclass
  NewUser = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.NewUser").msgclass
  GetUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.GetUserResponse").msgclass
  BillingMeta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.BillingMeta").msgclass
  Credentials = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Credentials").msgclass
  JWT = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.JWT").msgclass
  PasswordResetInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.PasswordResetInput").msgclass
  Username = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Username").msgclass
end
