# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/member/a_rpc.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/empty_pb'
require 'io/common/common_objects_pb'
require 'io/common/message_pb'
require 'io/common/pagination_pb'
require 'io/common/filter_pb'
require 'io/member/member_events_pb'
require 'io/member/member_pb'
require 'io/member/program_pb'
require 'io/member/tier_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/member/a_rpc.proto", :syntax => :proto3) do
  end
end

module Members
end
