# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/member/member.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/proximity_pb'
require 'io/common/message_pb'
require 'io/common/metrics_pb'
require 'io/common/note_pb'
require 'io/common/pagination_pb'
require 'io/common/filter_pb'
require 'io/common/pass_pb'
require 'io/common/personal_pb'
require 'io/common/expiry_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/member/member.proto", :syntax => :proto3) do
    add_message "members.Member" do
      optional :id, :string, 1
      optional :externalId, :string, 2
      optional :groupingIdentifier, :string, 3
      optional :tierId, :string, 4
      optional :programId, :string, 5
      optional :person, :message, 6, "io.Person"
      map :metaData, :string, :string, 7
      optional :optOut, :bool, 13
      optional :points, :float, 14
      optional :secondaryPoints, :float, 15
      optional :tierPoints, :uint32, 16
      optional :expiryDate, :message, 18, "google.protobuf.Timestamp"
      optional :status, :enum, 19, "members.MemberStatus"
      optional :passOverrides, :message, 20, "io.PassOverrides"
      optional :passMetaData, :message, 21, "io.Metadata"
      repeated :notes, :message, 26, "io.Note"
      optional :currentTierAwarded, :message, 27, "google.protobuf.Timestamp"
      optional :currentTierExpires, :message, 28, "google.protobuf.Timestamp"
      optional :created, :message, 29, "google.protobuf.Timestamp"
      optional :updated, :message, 30, "google.protobuf.Timestamp"
      optional :profileImage, :string, 31
    end
    add_message "members.MemberRecordByExternalIdRequest" do
      optional :programId, :string, 1
      optional :externalId, :string, 2
    end
    add_message "members.MemberSegmentRequest" do
      optional :filter, :message, 1, "io.Filter"
      optional :newValues, :message, 2, "members.Member"
    end
    add_message "members.UpdateExpiryRequest" do
      optional :programId, :string, 1
      optional :tierId, :string, 2
      optional :expirySettings, :message, 3, "io.ExpirySettings"
      optional :timezone, :string, 4
    end
    add_message "members.MemberPoints" do
      optional :id, :string, 1
      optional :externalId, :string, 2
      optional :programId, :string, 3
      optional :points, :float, 4
      optional :secondaryPoints, :float, 5
      optional :tierPoints, :uint32, 6
    end
    add_message "members.EarnBurnPointsRequest" do
      optional :id, :string, 1
      optional :externalId, :string, 2
      optional :programId, :string, 3
      optional :points, :float, 4
      optional :secondaryPoints, :float, 5
      optional :tierPoints, :uint32, 6
    end
    add_message "members.SetPointsRequest" do
      optional :id, :string, 1
      optional :externalId, :string, 2
      optional :programId, :string, 3
      optional :points, :float, 4
      optional :secondaryPoints, :float, 5
      optional :tierPoints, :uint32, 6
      optional :resetPoints, :bool, 7
      optional :resetSecondaryPoints, :bool, 8
      optional :resetTierPoints, :bool, 9
    end
    add_message "members.MemberCheckInOutRequest" do
      optional :id, :string, 1
      optional :externalId, :string, 2
      optional :location, :message, 3, "io.GPSLocation"
      optional :timestamp, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "members.ListRequestDeprecated" do
      optional :programId, :string, 1
      optional :pagination, :message, 2, "io.Pagination"
    end
    add_message "members.ListRequest" do
      optional :programId, :string, 1
      optional :filters, :message, 2, "io.Filters"
      optional :emailAsCsv, :bool, 3
    end
    add_enum "members.MemberStatus" do
      value :ENROLLED, 0
      value :ACTIVE, 1
      value :EXPIRED, 3
      value :DELETED, 5
    end
  end
end

module Members
  Member = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.Member").msgclass
  MemberRecordByExternalIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.MemberRecordByExternalIdRequest").msgclass
  MemberSegmentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.MemberSegmentRequest").msgclass
  UpdateExpiryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.UpdateExpiryRequest").msgclass
  MemberPoints = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.MemberPoints").msgclass
  EarnBurnPointsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.EarnBurnPointsRequest").msgclass
  SetPointsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.SetPointsRequest").msgclass
  MemberCheckInOutRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.MemberCheckInOutRequest").msgclass
  ListRequestDeprecated = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.ListRequestDeprecated").msgclass
  ListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.ListRequest").msgclass
  MemberStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.MemberStatus").enummodule
end
