# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/member/member_events.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/personal_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/member/member_events.proto", :syntax => :proto3) do
    add_message "members.MemberEvent" do
      optional :id, :string, 1
      optional :member, :message, 2, "members.MemberMininmal"
      optional :eventType, :enum, 3, "members.MemberEvents"
      optional :address, :string, 4
      optional :lat, :double, 5
      optional :lon, :double, 6
      optional :alt, :int32, 7
      optional :externalId, :string, 8
      optional :externalUserId, :string, 9
      optional :externalDeviceId, :string, 10
      optional :externalServiceId, :string, 11
      map :metaData, :string, :string, 12
      optional :notes, :string, 13
      optional :date, :message, 14, "google.protobuf.Timestamp"
      optional :retainedUntilDate, :message, 15, "google.protobuf.Timestamp"
      optional :created, :message, 16, "google.protobuf.Timestamp"
    end
    add_message "members.MemberMininmal" do
      optional :id, :string, 1
      optional :externalId, :string, 2
      optional :groupingIdentifier, :string, 3
      optional :tierId, :string, 4
      optional :programId, :string, 5
      optional :person, :message, 6, "io.Person"
    end
    add_enum "members.MemberEvents" do
      value :EVENT_MEMBER_DO_NOT_USE, 0
      value :EVENT_MEMBER_CHECKED_IN, 1
      value :EVENT_MEMBER_CHECKED_OUT, 2
      value :EVENT_MEMBER_VERIFIED, 3
      value :EVENT_MEMBER_POINTS_EARNED, 4
      value :EVENT_MEMBER_POINTS_BURNED, 5
      value :EVENT_MEMBER_POINTS_SET, 6
    end
  end
end

module Members
  MemberEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.MemberEvent").msgclass
  MemberMininmal = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.MemberMininmal").msgclass
  MemberEvents = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.MemberEvents").enummodule
end
