# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/member/program.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/callback_pb'
require 'io/common/distribution_pb'
require 'io/common/localization_pb'
require 'io/common/metrics_pb'
require 'io/common/project_pb'
require 'io/common/billing_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/member/program.proto", :syntax => :proto3) do
    add_message "members.PointsType" do
      optional :balanceType, :enum, 1, "members.BalanceType"
      optional :currencyCode, :string, 2
    end
    add_message "members.Program" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :localizedName, :message, 3, "io.LocalizedString"
      repeated :status, :enum, 4, "io.ProjectStatus"
      optional :quota, :message, 5, "io.Quota"
      optional :passTypeIdentifier, :string, 6
      optional :distributionSettings, :message, 7, "io.DistributionSettings"
      optional :autoDeleteDaysAfterExpiry, :uint32, 8
      optional :autoReminderDaysBeforeExpiry, :uint32, 9
      optional :expiryMessage, :string, 10
      optional :localizedExpiryMessage, :message, 11, "io.LocalizedString"
      optional :autoDeleteDaysAfterNotInstalling, :uint32, 12
      map :callbacks, :uint32, :message, 14, "io.Callback"
      optional :pointsType, :message, 16, "members.PointsType"
      optional :secondaryPointsType, :message, 17, "members.PointsType"
      optional :metrics, :message, 19, "io.Metrics"
      repeated :metaFieldsList, :string, 20
      optional :created, :message, 21, "google.protobuf.Timestamp"
      optional :updated, :message, 22, "google.protobuf.Timestamp"
      optional :profileImageSettings, :enum, 23, "members.ProfileImageSetting"
      optional :applyFieldToExternalIdOnEnrol, :message, 24, "members.CustomExternalId"
      optional :eventCaptureSettings, :message, 25, "members.EventCaptureSettings"
    end
    add_message "members.EventCaptureSettings" do
      map :eventDataRetentionSettings, :uint32, :uint32, 1
      optional :smsConfirmUponCheckIn, :bool, 2
      optional :emailConfirmUponCheckIn, :bool, 3
    end
    add_message "members.ProgramCopyRequest" do
      optional :id, :string, 1
      optional :name, :string, 2
      repeated :status, :enum, 3, "io.ProjectStatus"
      optional :passTypeIdentifier, :string, 4
    end
    add_message "members.ListProgramsResponse" do
      repeated :programs, :message, 1, "members.Program"
    end
    add_message "members.GetMetaKeysResponse" do
      repeated :keys, :string, 1
    end
    add_message "members.CustomExternalId" do
      optional :fieldUniqueName, :string, 1
      optional :errorMessage, :string, 2
    end
    add_enum "members.ProgramAutoUpDownGradeTierType" do
      value :UPDOWNGRADE_POINTS, 0
      value :UPDOWNGRADE_SECONDARY_POINTS, 1
      value :UPDOWNGRADE_TIER_POINTS, 2
      value :UPDOWNGRADE_VISITS, 3
    end
    add_enum "members.BalanceType" do
      value :BALANCE_TYPE_STRING, 0
      value :BALANCE_TYPE_INT, 1
      value :BALANCE_TYPE_DOUBLE, 2
      value :BALANCE_TYPE_MONEY, 3
    end
    add_enum "members.ProfileImageSetting" do
      value :PROFILE_IMAGE_NONE, 0
      value :PROFILE_IMAGE_OPTIONAL, 1
      value :PROFILE_IMAGE_REQUIRED, 2
    end
  end
end

module Members
  PointsType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.PointsType").msgclass
  Program = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.Program").msgclass
  EventCaptureSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.EventCaptureSettings").msgclass
  ProgramCopyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.ProgramCopyRequest").msgclass
  ListProgramsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.ListProgramsResponse").msgclass
  GetMetaKeysResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.GetMetaKeysResponse").msgclass
  CustomExternalId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.CustomExternalId").msgclass
  ProgramAutoUpDownGradeTierType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.ProgramAutoUpDownGradeTierType").enummodule
  BalanceType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.BalanceType").enummodule
  ProfileImageSetting = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.ProfileImageSetting").enummodule
end
