# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/member/tier.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/localization_pb'
require 'io/common/common_objects_pb'
require 'io/common/expiry_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/member/tier.proto", :syntax => :proto3) do
    add_message "members.Tier" do
      optional :id, :string, 1
      optional :tierIndex, :uint32, 2
      optional :name, :string, 3
      optional :localizedName, :message, 4, "io.LocalizedString"
      optional :secondaryTierName, :string, 5
      optional :localizedSecondaryTierName, :message, 6, "io.LocalizedString"
      optional :programId, :string, 7
      optional :passTemplateId, :string, 8
      optional :tierUpgradeMessage, :string, 9
      optional :localizedTierUpgradeMessage, :message, 10, "io.LocalizedString"
      optional :tierDowngradeMessage, :string, 11
      optional :localizedTierDowngradeMessage, :message, 12, "io.LocalizedString"
      optional :created, :message, 13, "google.protobuf.Timestamp"
      optional :updated, :message, 14, "google.protobuf.Timestamp"
      optional :pointsOverdrawn, :bool, 15
      optional :secondaryPointsOverdrawn, :bool, 16
      optional :expirySettings, :message, 17, "io.ExpirySettings"
      optional :timezone, :string, 18
    end
    add_message "members.TierRequestInput" do
      optional :programId, :string, 1
      optional :tierId, :string, 2
    end
  end
end

module Members
  Tier = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.Tier").msgclass
  TierRequestInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.TierRequestInput").msgclass
end
