# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: io/core/a_rpc_images.proto for package 'io'

require 'grpc'
require 'io/core/a_rpc_images_pb'

module Io
  module Images
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'io.Images'

      rpc :setProfileImage, ::Io::ProfileImageInput, ::Google::Protobuf::Empty
      rpc :getProfileImage, ::Google::Protobuf::Empty, ::Io::Url
      rpc :createImages, ::Io::CreateImageInput, ::Io::ImageIds
      rpc :updateImage, ::Io::UpdateImageInput, ::Io::ImageRecord
      rpc :getImageURL, ::Io::Id, ::Io::Url
      rpc :getStampImageURL, ::Io::StampImageRequest, ::Io::Url
      rpc :getStampImageConfig, ::Io::Id, ::Io::StampImageConfig
      rpc :updateStampImageConfig, ::Io::StampImageConfig, ::Io::Id
      rpc :getStampImagePreview, ::Io::StampImagePreviewRequest, ::Io::StampImagePreview
      rpc :getLocalizedImageURL, ::Io::LocalizedImageInput, ::Io::Url
      rpc :getProfileImageById, ::Io::Id, ::Io::Url
      # returns a zip bundle containing all images for that ID
      rpc :getImageBundle, ::Io::Id, ::Io::ImageBundle
      rpc :getImageData, ::Io::Id, ::Io::ImageRecord
      rpc :deleteImage, ::Io::Id, ::Google::Protobuf::Empty
      rpc :deleteLocalizedImage, ::Io::LocalizedImageInput, ::Io::ImageRecord
      rpc :listImagesForUserDeprecated, ::Io::Pagination, stream(::Io::ImageRecord)
      rpc :listImagesForUser, ::Io::Filters, stream(::Io::ImageRecord)
      rpc :listImagesDeprecated, ::Io::Pagination, stream(::Io::ImageRecord)
      rpc :listImages, ::Io::Filters, stream(::Io::ImageRecord)
      rpc :countImagesDeprecated, ::Io::Pagination, ::Io::Count
      rpc :countImages, ::Io::Filters, ::Io::Count
      rpc :countImagesForUserDeprecated, ::Io::Pagination, ::Io::Count
      rpc :countImagesForUser, ::Io::Filters, ::Io::Count
    end

    Stub = Service.rpc_stub_class
  end
end
