# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: io/scheduler/a_rpc.proto for package 'scheduler'
# Original file comments:
# *
# Scheduler RPC
#
# The PassKit Scheduler API lets you schedule a job.

require 'grpc'
require 'io/scheduler/a_rpc_pb'

module Scheduler
  module Scheduler
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'scheduler.Scheduler'

      rpc :createSchedulingJob, ::Ct::SchedulingJob, ::Ct::SchedulingJobResponse
      rpc :getSchedulingJob, ::Io::Id, ::Ct::SchedulingJob
      rpc :updateSchedulingJob, ::Ct::SchedulingJob, ::Ct::SchedulingJobResponse
      rpc :patchSchedulingJob, ::Ct::SchedulingJob, ::Ct::SchedulingJobResponse
      rpc :deleteSchedulingJob, ::Io::Id, ::Google::Protobuf::Empty
      rpc :getSchedulingJobHistory, ::Io::Id, ::Ct::JobHistory
      rpc :listSchedulingJobHistories, ::Scheduler::ListRequest, stream(::Ct::JobHistory)
    end

    Stub = Service.rpc_stub_class
  end
end
