# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: io/analytics/a_rpc.proto for package 'analytics'
# Original file comments:
# *
# Analytics RPC
#
# The PassKit Analytics API lets you track the performance of Apple Wallet and Google Wallet passes.

require 'grpc'
require 'io/analytics/a_rpc_pb'

module Analytics
  module Analytics
    # Analytics provides access to daily, monthly, or yearly analytics reports.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'analytics.Analytics'

      # Retrieves analytics data for a class or project, such as daily check-ins, installs, redemptions, etc. Required fields: classId, protocol.
      rpc :getAnalytics, ::Io::AnalyticsRequest, ::Io::AnalyticsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
