# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/core/a_rpc_others.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/empty_pb'
require 'io/common/common_objects_pb'
require 'io/common/project_pb'
require 'io/common/message_pb'
require 'io/common/job_pb'
require 'io/common/pagination_pb'
require 'io/common/filter_pb'
require 'io/common/integration_pb'
require 'io/user/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/core/a_rpc_others.proto", :syntax => :proto3) do
  end
end

module Io
end
