# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: io/core/a_rpc_templates.proto for package 'io'

require 'grpc'
require 'io/core/a_rpc_templates_pb'

module Io
  module Templates
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'io.Templates'

      rpc :createTemplate, Io::PassTemplate, Io::Id
      rpc :updateTemplate, Io::PassTemplate, Io::PassTemplate
      rpc :getTemplate, Io::Id, Io::PassTemplateResponse
      rpc :getDefaultTemplate, Io::DefaultTemplateRequest, Io::PassTemplate
      rpc :copyTemplate, Io::CopyObjectInput, Io::Id
      rpc :deleteTemplate, Io::Id, Google::Protobuf::Empty
      rpc :listTemplatesForUserDeprecated, Io::Pagination, stream(Io::PassTemplateResponse)
      rpc :listTemplatesForUser, Io::Filters, stream(Io::PassTemplateResponse)
      rpc :listTemplatesDeprecated, Io::Pagination, stream(Io::PassTemplateResponse)
      rpc :listTemplates, Io::Filters, stream(Io::PassTemplateResponse)
      rpc :countTemplatesDeprecated, Io::Pagination, Io::Count
      rpc :countTemplates, Io::Filters, Io::Count
      rpc :countTemplatesForUserDeprecated, Io::Pagination, Io::Count
      rpc :countTemplatesForUser, Io::Filters, Io::Count
      rpc :createLocation, Io::GPSLocation, Io::Id
      rpc :updateLocation, Io::GPSLocation, Io::GPSLocation
      rpc :getLocation, Io::Id, Io::GPSLocation
      rpc :listLocationsDeprecated, Io::Pagination, stream(Io::GPSLocation)
      rpc :listLocations, Io::Filters, stream(Io::GPSLocation)
      rpc :copyLocation, Io::CopyObjectInput, Io::Id
      rpc :deleteLocation, Io::Id, Google::Protobuf::Empty
      rpc :countLocationsDeprecated, Io::Pagination, Io::Count
      rpc :countLocations, Io::Filters, Io::Count
      rpc :createBeacon, Io::Beacon, Io::Id
      rpc :updateBeacon, Io::Beacon, Io::Beacon
      rpc :getBeacon, Io::Id, Io::Beacon
      rpc :listBeaconsDeprecated, Io::Pagination, stream(Io::Beacon)
      rpc :listBeacons, Io::Filters, stream(Io::Beacon)
      rpc :copyBeacon, Io::CopyObjectInput, Io::Id
      rpc :deleteBeacon, Io::Id, Google::Protobuf::Empty
      rpc :countBeaconsDeprecated, Io::Pagination, Io::Count
      rpc :countBeacons, Io::Filters, Io::Count
      rpc :createLink, Io::Link, Io::Id
      rpc :updateLink, Io::Link, Io::Link
      rpc :getLink, Io::Id, Io::Link
      rpc :listLinksDeprecated, Io::Pagination, stream(Io::Link)
      rpc :listLinks, Io::Filters, stream(Io::Link)
      rpc :copyLink, Io::CopyObjectInput, Io::Id
      rpc :deleteLink, Io::Id, Google::Protobuf::Empty
      rpc :countLinksDeprecated, Io::Pagination, Io::Count
      rpc :countLinks, Io::Filters, Io::Count
    end

    Stub = Service.rpc_stub_class
  end
end
