# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/core/a_rpc_certificates.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/empty_pb'
require 'io/common/common_objects_pb'
require 'io/certificate/certificate_pb'
require 'io/common/pagination_pb'
require 'io/common/filter_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/core/a_rpc_certificates.proto", :syntax => :proto3) do
  end
end

module Io
end
