# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/core/a_rpc_distribution.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/empty_pb'
require 'io/common/common_objects_pb'
require 'io/common/distribution_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/core/a_rpc_distribution.proto", :syntax => :proto3) do
  end
end

module Io
end
