# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/single_use_coupons/a_rpc.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/api/annotations_pb'
require 'io/common/common_objects_pb'
require 'io/common/pagination_pb'
require 'io/common/filter_pb'
require 'io/common/reporting_pb'
require 'io/single_use_coupons/campaign_pb'
require 'io/single_use_coupons/offer_pb'
require 'io/single_use_coupons/coupon_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/single_use_coupons/a_rpc.proto", :syntax => :proto3) do
  end
end

module SingleUseCoupons
end
