# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/single_use_coupons/coupon.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/pagination_pb'
require 'io/common/filter_pb'
require 'io/common/pass_pb'
require 'io/common/personal_pb'
require 'io/common/metrics_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/single_use_coupons/coupon.proto", :syntax => :proto3) do
    add_message "single_use_coupons.Coupon" do
      optional :id, :string, 1
      optional :externalId, :string, 2
      optional :offerId, :string, 3
      optional :campaignId, :string, 4
      optional :person, :message, 5, "io.Person"
      map :metaData, :string, :string, 6
      optional :sku, :string, 7
      optional :optOut, :bool, 8
      optional :status, :enum, 10, "single_use_coupons.CouponStatus"
      optional :expiryDate, :message, 11, "google.protobuf.Timestamp"
      optional :redemptionDetails, :message, 12, "single_use_coupons.RedemptionDetails"
      optional :passOverrides, :message, 13, "io.PassOverrides"
      optional :passMetaData, :message, 14, "io.Metadata"
      optional :created, :message, 15, "google.protobuf.Timestamp"
      optional :updated, :message, 16, "google.protobuf.Timestamp"
    end
    add_message "single_use_coupons.RedemptionDetails" do
      optional :redemptionDate, :message, 1, "google.protobuf.Timestamp"
      optional :redemptionCode, :string, 2
      optional :lat, :double, 3
      optional :lon, :double, 4
      optional :alt, :int32, 5
      optional :redemptionSource, :string, 6
      optional :redemptionReference, :string, 7
      optional :transactionReference, :string, 8
      optional :transactionAmount, :double, 9
      map :metaData, :string, :string, 10
    end
    add_message "single_use_coupons.ExternalIdRequest" do
      optional :couponCampaignId, :string, 1
      optional :externalId, :string, 2
    end
    add_message "single_use_coupons.ListRequestDeprecated" do
      optional :couponCampaignId, :string, 1
      optional :pagination, :message, 2, "io.Pagination"
    end
    add_message "single_use_coupons.ListRequest" do
      optional :couponCampaignId, :string, 1
      optional :filters, :message, 2, "io.Filters"
      optional :emailAsCsv, :bool, 3
    end
    add_enum "single_use_coupons.CouponStatus" do
      value :UNREDEEMED, 0
      value :REDEEMED, 1
    end
  end
end

module SingleUseCoupons
  Coupon = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.Coupon").msgclass
  RedemptionDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.RedemptionDetails").msgclass
  ExternalIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.ExternalIdRequest").msgclass
  ListRequestDeprecated = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.ListRequestDeprecated").msgclass
  ListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.ListRequest").msgclass
  CouponStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.CouponStatus").enummodule
end
