# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/single_use_coupons/offer.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/billing_pb'
require 'io/common/distribution_pb'
require 'io/common/localization_pb'
require 'io/common/pagination_pb'
require 'io/common/filter_pb'
require 'io/common/template_pb'
require 'io/image/image_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/single_use_coupons/offer.proto", :syntax => :proto3) do
    add_message "single_use_coupons.CouponOffer" do
      optional :id, :string, 1
      optional :offerTitle, :string, 2
      optional :localizedOfferTitle, :message, 3, "io.LocalizedString"
      optional :offerShortTitle, :string, 4
      optional :localizedOfferShortTitle, :message, 5, "io.LocalizedString"
      optional :offerDetails, :string, 6
      optional :localizedOfferDetails, :message, 7, "io.LocalizedString"
      optional :offerFinePrint, :string, 8
      optional :localizedOfferFinePrint, :message, 9, "io.LocalizedString"
      optional :beforeRedeemPassTemplateId, :string, 10
      optional :afterRedeemPassTemplateId, :string, 11
      optional :quota, :message, 12, "io.Quota"
      optional :couponExpirySettings, :message, 13, "single_use_coupons.CouponExpirySettings"
      optional :redemptionSettings, :message, 14, "single_use_coupons.RedemptionSettings"
      optional :issueStartDate, :message, 15, "google.protobuf.Timestamp"
      optional :issueEndDate, :message, 16, "google.protobuf.Timestamp"
      optional :created, :message, 17, "google.protobuf.Timestamp"
      optional :updated, :message, 18, "google.protobuf.Timestamp"
      optional :campaignId, :string, 19
      optional :distributionSettings, :message, 20, "io.DistributionSettings"
      optional :shortCode, :string, 21
      optional :ianaTimezone, :string, 22
      optional :disabled, :bool, 23
    end
    add_message "single_use_coupons.CouponExpirySettings" do
      optional :couponExpiryType, :enum, 1, "single_use_coupons.CouponExpiryType"
      optional :expireAfterXDays, :uint32, 3
    end
    add_message "single_use_coupons.RedemptionSettings" do
      optional :redemptionStartDate, :message, 1, "google.protobuf.Timestamp"
      optional :redemptionEndDate, :message, 2, "google.protobuf.Timestamp"
      repeated :redemptionType, :enum, 3, "single_use_coupons.RedemptionType"
      optional :codeProvidedOnRedeemSettings, :message, 5, "single_use_coupons.CustomerInitiatedCodeProvideOnRedeemSettings"
      optional :fixedCodeSettings, :message, 6, "single_use_coupons.CustomerInitiatedFixedCodeSettings"
      optional :standardSettings, :message, 7, "single_use_coupons.StandardPassKitHostedPage"
    end
    add_message "single_use_coupons.CustomerInitiatedFixedCodeSettings" do
      optional :fixedCode, :string, 1
      optional :useCouponSku, :bool, 2
      optional :barcode, :enum, 3, "io.BarcodeType"
      optional :redemptionTimer, :message, 4, "single_use_coupons.RedemptionTimerSettings"
    end
    add_message "single_use_coupons.RedemptionTimerSettings" do
      optional :timeoutSeconds, :uint32, 1
      optional :timerHelpText, :string, 2
      optional :localizedTimeHelpText, :message, 3, "io.LocalizedString"
    end
    add_message "single_use_coupons.CustomerInitiatedCodeProvideOnRedeemSettings" do
      repeated :validCodes, :string, 1
      optional :redemptionCodeInput, :message, 2, "single_use_coupons.InputField"
      optional :submitButtonText, :string, 3
      optional :localizedSubmitButtonText, :message, 4, "io.LocalizedString"
    end
    add_message "single_use_coupons.InputField" do
      optional :label, :string, 1
      optional :localizedLabel, :message, 2, "io.LocalizedString"
      optional :helperText, :string, 3
      optional :localizedHelperText, :message, 4, "io.LocalizedString"
      optional :errorMessage, :string, 5
      optional :localizedErrorMessage, :message, 6, "io.LocalizedString"
      optional :defaultValue, :string, 7
      optional :localizedDefaultValue, :message, 8, "io.LocalizedString"
      optional :placeholder, :string, 9
      optional :localizedPlaceholder, :message, 10, "io.LocalizedString"
      optional :validation, :string, 11
    end
    add_message "single_use_coupons.StandardPassKitHostedPage" do
      optional :title, :string, 1
      optional :localizedTitle, :message, 2, "io.LocalizedString"
      optional :redemptionInstructions, :string, 3
      optional :localizedRedemptionInstructions, :message, 4, "io.LocalizedString"
      optional :footerText, :string, 7
      optional :localizedFooterText, :message, 8, "io.LocalizedString"
      optional :responseTexts, :message, 9, "single_use_coupons.ResponseTexts"
      optional :hideRedeemedDateTime, :bool, 10
      optional :callToActionButton, :message, 11, "single_use_coupons.CallToActionButton"
      optional :cssOverrides, :string, 12
      oneof :RedemptionImageAssets do
        optional :imageIds, :message, 5, "io.ImageIds"
        optional :images, :message, 6, "io.ImageData"
      end
    end
    add_message "single_use_coupons.CallToActionButton" do
      optional :hideCallToActionButton, :bool, 1
      optional :buttonText, :string, 2
      optional :localizedButtonText, :message, 3, "io.LocalizedString"
      optional :link, :string, 4
      optional :localizedLink, :message, 5, "io.LocalizedString"
    end
    add_message "single_use_coupons.ResponseTexts" do
      optional :redeemConfirmationDialogBoxText, :string, 1
      optional :localizedRedeemConfirmationDialogBoxText, :message, 2, "io.LocalizedString"
      optional :cancelRedeemText, :string, 3
      optional :localizedCancelRedeemText, :message, 4, "io.LocalizedString"
      optional :afterRedeemText, :string, 5
      optional :localizedAfterRedeemText, :message, 6, "io.LocalizedString"
      optional :couponAlreadyRedeemedText, :string, 7
      optional :localizedCouponAlreadyRedeemedText, :message, 8, "io.LocalizedString"
      optional :offerExpiredText, :string, 9
      optional :localizedOfferExpiredText, :message, 10, "io.LocalizedString"
      optional :couponExpiredText, :string, 11
      optional :localizedCouponExpiredText, :message, 12, "io.LocalizedString"
    end
    add_message "single_use_coupons.CouponOffersListRequestDeprecated" do
      optional :campaignId, :string, 1
      optional :pagination, :message, 2, "io.Pagination"
    end
    add_message "single_use_coupons.CouponOffersListRequest" do
      optional :campaignId, :string, 1
      optional :filters, :message, 2, "io.Filters"
    end
    add_enum "single_use_coupons.CouponExpiryType" do
      value :EXPIRY_DO_NOT_USE, 0
      value :AUTO_EXPIRE_OFFER_END_DATE, 1
      value :AUTO_EXPIRE_REDEMPTION_END_DATE, 2
      value :EXPIRE_AFTER_X_DAYS, 3
      value :EXPIRE_ON_VARIABLE_DATE_TIME, 4
    end
    add_enum "single_use_coupons.RedemptionType" do
      value :REDEMPTION_TYPE_DO_NOT_USE, 0
      value :REDEMPTION_TYPE_API, 1
      value :REDEMPTION_TYPE_CUSTOMER_INITIATED, 2
      value :REDEMPTION_TYPE_CUSTOMER_INITIATED_CODE_FIXED, 3
      value :REDEMPTION_TYPE_CUSTOMER_INITIATED_CODE_PROVIDED_ON_REDEEM, 4
    end
  end
end

module SingleUseCoupons
  CouponOffer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.CouponOffer").msgclass
  CouponExpirySettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.CouponExpirySettings").msgclass
  RedemptionSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.RedemptionSettings").msgclass
  CustomerInitiatedFixedCodeSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.CustomerInitiatedFixedCodeSettings").msgclass
  RedemptionTimerSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.RedemptionTimerSettings").msgclass
  CustomerInitiatedCodeProvideOnRedeemSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.CustomerInitiatedCodeProvideOnRedeemSettings").msgclass
  InputField = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.InputField").msgclass
  StandardPassKitHostedPage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.StandardPassKitHostedPage").msgclass
  CallToActionButton = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.CallToActionButton").msgclass
  ResponseTexts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.ResponseTexts").msgclass
  CouponOffersListRequestDeprecated = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.CouponOffersListRequestDeprecated").msgclass
  CouponOffersListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.CouponOffersListRequest").msgclass
  CouponExpiryType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.CouponExpiryType").enummodule
  RedemptionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("single_use_coupons.RedemptionType").enummodule
end
