# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/flights/cabin_codes/cabin_codes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/flights/cabin_codes/cabin_codes.proto", :syntax => :proto3) do
    add_enum "cabin_codes.CompartmentCode" do
      value :NONE, 0
      value :R, 1
      value :P, 2
      value :F, 3
      value :A, 4
      value :J, 5
      value :C, 6
      value :D, 7
      value :I, 8
      value :Z, 9
      value :W, 10
      value :E, 11
      value :S, 12
      value :Y, 13
      value :B, 14
      value :H, 15
      value :K, 16
      value :L, 17
      value :M, 18
      value :N, 19
      value :O, 20
      value :Q, 21
      value :T, 22
      value :V, 23
      value :X, 24
      value :G, 25
      value :U, 26
    end
  end
end

module CabinCodes
  CompartmentCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cabin_codes.CompartmentCode").enummodule
end
