# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/attributes.proto

require 'google/protobuf'


descriptor_data = "\n\x1aio/common/attributes.proto\x12\x02io*\xe4\x01\n\x10\x44\x65viceAttributes\x12\x10\n\x0cNoAttributes\x10\x00\x12\x07\n\x03Ios\x10\x01\x12\x0b\n\x07\x41ndroid\x10\x02\x12\x11\n\rSupportWallet\x10\x04\x12\x11\n\rWalletScanner\x10\x08\x12\x10\n\x0cWalletDaemon\x10\x10\x12\x10\n\x0cWalletPasses\x10 \x12\x0b\n\x07Windows\x10@\x12\x08\n\x03OSX\x10\x80\x01\x12\n\n\x05Linux\x10\x80\x02\x12\x0b\n\x06Mobile\x10\x80\x04\x12\x0c\n\x07\x44\x65sktop\x10\x80\x08\x12\x0b\n\x06Tablet\x10\x80\x10\x12\x13\n\x0eUnsupportedIos\x10\x80 */\n\x07\x43hannel\x12\x12\n\x0eUnknownChannel\x10\x00\x12\x07\n\x03Web\x10\x01\x12\x07\n\x03\x41PI\x10\x02*U\n\x0e\x41uthentication\x12\x13\n\x0fUnauthenticated\x10\x00\x12\x0c\n\x08WebToken\x10\x01\x12\x0f\n\x0b\x42\x65\x61rerToken\x10\x02\x12\x0f\n\x0b\x43\x65rtificate\x10\x03*9\n\x08UserType\x12\x13\n\x0fUnknownUserType\x10\x00\x12\x08\n\x04User\x10\x01\x12\x0e\n\nTeamMember\x10\x02\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  DeviceAttributes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DeviceAttributes").enummodule
  Channel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Channel").enummodule
  Authentication = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Authentication").enummodule
  UserType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.UserType").enummodule
end
