# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/batch_update.proto

require 'google/protobuf'

require 'io/common/filter_pb'


descriptor_data = "\n\x1cio/common/batch_update.proto\x12\x02io\x1a\x16io/common/filter.proto\"}\n\x11\x42\x61tchUpdateMember\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03\x63Id\x18\x02 \x01(\r\x12\x12\n\nprotocolId\x18\x03 \x01(\t\x12\x12\n\nmemberUUID\x18\x04 \x01(\t\x12\'\n\x07request\x18\x05 \x01(\x0b\x32\x16.io.BatchUpdateRequest\"t\n\x12\x42\x61tchUpdateRequest\x12\x0f\n\x07\x63lassId\x18\x01 \x01(\t\x12%\n\x0c\x66ilterGroups\x18\x02 \x03(\x0b\x32\x0f.io.FilterGroup\x12&\n\rupdateEntries\x18\x03 \x03(\x0b\x32\x0f.io.UpdateEntry\"T\n\x0bUpdateEntry\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\'\n\nupdateType\x18\x03 \x01(\x0e\x32\x13.io.BatchUpdateType*S\n\x0f\x42\x61tchUpdateType\x12\x1b\n\x17\x42\x41TCH_UPDATE_DO_NOT_USE\x10\x00\x12\x07\n\x03SET\x10\x01\x12\x0c\n\x08INCREASE\x10\x02\x12\x0c\n\x08\x44\x45\x43REASE\x10\x03\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  BatchUpdateMember = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.BatchUpdateMember").msgclass
  BatchUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.BatchUpdateRequest").msgclass
  UpdateEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.UpdateEntry").msgclass
  BatchUpdateType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.BatchUpdateType").enummodule
end
