# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/billing.proto

require 'google/protobuf'


descriptor_data = "\n\x17io/common/billing.proto\x12\x02io\"r\n\x05Quota\x12\'\n\x07\x64\x65tails\x18\x01 \x03(\x0b\x32\x16.io.Quota.DetailsEntry\x1a@\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.io.QuotaDetails:\x02\x38\x01\"-\n\x0cQuotaDetails\x12\r\n\x05quota\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x04\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  Quota = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Quota").msgclass
  QuotaDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.QuotaDetails").msgclass
end
