# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/featured_actions.proto

require 'google/protobuf'


descriptor_data = "\n io/common/featured_actions.proto\x12\x02io\"W\n\x0e\x46\x65\x61turedAction\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.io.FeaturedActionType\x12\x0b\n\x03url\x18\x03 \x01(\t*\xa8\x02\n\x12\x46\x65\x61turedActionType\x12\x1e\n\x1a\x46\x45\x41TURED_ACTION_DO_NOT_USE\x10\x00\x12\x11\n\rVIEW_SCHEDULE\x10\x01\x12\x11\n\rWATCH_TRAILER\x10\x02\x12\x13\n\x0fLISTEN_TO_MUSIC\x10\x03\x12\t\n\x05PLACE\x10\x04\x12\x08\n\x04SHOP\x10\x05\x12\x12\n\x0e\x41\x44\x44_TO_BALANCE\x10\x06\x12\r\n\tTELEPHONE\x10\x07\x12\x17\n\x13VIEW_OFFERS_REWARDS\x10\x08\x12\r\n\tBOOK_STAY\x10\t\x12\x0f\n\x0b\x42OOK_FLIGHT\x10\n\x12\x0c\n\x08\x42OOK_CAR\x10\x0b\x12\x14\n\x10\x42OOK_APPOINTMENT\x10\x0c\x12\x17\n\x13MEMBERSHIP_BENEFITS\x10\r\x12\t\n\x05ORDER\x10\x0e\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  FeaturedAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.FeaturedAction").msgclass
  FeaturedActionType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.FeaturedActionType").enummodule
end
