# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/filter.proto

require 'google/protobuf'



descriptor_data = "\n\x16io/common/filter.proto\x12\x02io\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xce\x01\n\x07\x46ilters\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12%\n\x0c\x66ilterGroups\x18\x03 \x03(\x0b\x32\x0f.io.FilterGroup\x12\x0f\n\x07orderBy\x18\x04 \x01(\t\x12\x10\n\x08orderAsc\x18\x05 \x01(\x08:Z\x92\x41W\nU*\nPagination2GFilters applies multiple filter conditions to retrieve matched records.\"O\n\x0b\x46ieldFilter\x12\x13\n\x0b\x66ilterField\x18\x01 \x01(\t\x12\x13\n\x0b\x66ilterValue\x18\x02 \x01(\t\x12\x16\n\x0e\x66ilterOperator\x18\x03 \x01(\t\"U\n\x0b\x46ilterGroup\x12\x1f\n\tcondition\x18\x01 \x01(\x0e\x32\x0c.io.Operator\x12%\n\x0c\x66ieldFilters\x18\x02 \x03(\x0b\x32\x0f.io.FieldFilter*\x1b\n\x08Operator\x12\x07\n\x03\x41ND\x10\x00\x12\x06\n\x02OR\x10\x01\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  Filters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Filters").msgclass
  FieldFilter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.FieldFilter").msgclass
  FilterGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.FilterGroup").msgclass
  Operator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Operator").enummodule
end
