# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/links.proto

require 'google/protobuf'

require 'io/common/common_objects_pb'
require 'io/common/localization_pb'


descriptor_data = "\n\x15io/common/links.proto\x12\x02io\x1a\x1eio/common/common_objects.proto\x1a\x1cio/common/localization.proto\"\xd3\x01\n\x04Link\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x1a\n\x04type\x18\x04 \x01(\x0e\x32\x0c.io.LinkType\x12*\n\rlocalizedLink\x18\x05 \x01(\x0b\x32\x13.io.LocalizedString\x12+\n\x0elocalizedTitle\x18\x06 \x01(\x0b\x32\x13.io.LocalizedString\x12\x1c\n\x05usage\x18\x07 \x03(\x0e\x32\r.io.UsageType\x12\x10\n\x08position\x18\x08 \x01(\r\"!\n\x06\x44\x62Link\x12\x17\n\x05links\x18\x01 \x03(\x0b\x32\x08.io.Link*k\n\x08LinkType\x12\x12\n\x0eURI_DO_NOT_USE\x10\x00\x12\x0b\n\x07URI_WEB\x10\x01\x12\x0b\n\x07URI_TEL\x10\x02\x12\r\n\tURI_EMAIL\x10\x03\x12\x10\n\x0cURI_LOCATION\x10\x04\x12\x10\n\x0cURI_CALENDAR\x10\x05\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  Link = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Link").msgclass
  DbLink = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DbLink").msgclass
  LinkType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.LinkType").enummodule
end
