# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/operation.proto

require 'google/protobuf'


descriptor_data = "\n\x19io/common/operation.proto\x12\x02io*M\n\tOperation\x12\x18\n\x14OPERATION_DO_NOT_USE\x10\x00\x12\x11\n\rOPERATION_PUT\x10\x01\x12\x13\n\x0fOPERATION_PATCH\x10\x02\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  Operation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Operation").enummodule
end
