# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/pagination.proto

require 'google/protobuf'



descriptor_data = "\n\x1aio/common/pagination.proto\x12\x02io\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xe0\x01\n\nPagination\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x13\n\x0b\x66ilterField\x18\x03 \x03(\t\x12\x13\n\x0b\x66ilterValue\x18\x04 \x03(\t\x12\x16\n\x0e\x66ilterOperator\x18\x05 \x03(\t\x12\x0f\n\x07orderBy\x18\x06 \x01(\t\x12\x10\n\x08orderAsc\x18\x07 \x01(\x08:N\x92\x41K\nI*\nPagination2;Pagination object used to split content into smaller parts.\"J\n\x06\x46ilter\x12\x13\n\x0b\x66ilterField\x18\x01 \x03(\t\x12\x13\n\x0b\x66ilterValue\x18\x02 \x03(\t\x12\x16\n\x0e\x66ilterOperator\x18\x03 \x03(\tBG\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  Pagination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Pagination").msgclass
  Filter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Filter").msgclass
end
