# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/pass.proto

require 'google/protobuf'

require 'io/image/image_pb'
require 'io/common/links_pb'
require 'io/common/metrics_pb'
require 'io/common/personal_pb'
require 'io/common/protocols_pb'
require 'io/common/proximity_pb'
require 'io/common/template_pb'


descriptor_data = "\n\x14io/common/pass.proto\x12\x02io\x1a\x14io/image/image.proto\x1a\x15io/common/links.proto\x1a\x17io/common/metrics.proto\x1a\x18io/common/personal.proto\x1a\x19io/common/protocols.proto\x1a\x19io/common/proximity.proto\x1a\x18io/common/template.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x84\x02\n\rPassOverrides\x12\x1e\n\x08imageIds\x18\x01 \x01(\x0b\x32\x0c.io.ImageIds\x12*\n\tlocations\x18\x03 \x03(\x0b\x32\x0f.io.GPSLocationB\x06\x92\x41\x03\xa0\x01\n\x12#\n\x07\x62\x65\x61\x63ons\x18\x04 \x03(\x0b\x32\n.io.BeaconB\x06\x92\x41\x03\xa0\x01\n\x12\x1f\n\x05links\x18\x05 \x03(\x0b\x32\x08.io.LinkB\x06\x92\x41\x03\xa0\x01\n\x12\x1a\n\x06\x63olors\x18\x06 \x01(\x0b\x32\n.io.Colors\x12\"\n\x1a\x61ssociatedStoreIdentifiers\x18\x07 \x03(\r\x12\x1b\n\x13\x61ppStoreIdentifiers\x18\x08 \x03(\x04J\x04\x08\x02\x10\x03\"\\\n\x0bPassOptions\x12&\n\x05\x61pple\x18\x01 \x01(\x0b\x32\x17.io.AppleWalletSettings\x12%\n\x06google\x18\x02 \x01(\x0b\x32\x15.io.GooglePaySettings\"\xff\x01\n\x04Pass\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63lassId\x18\x02 \x01(\t\x12\"\n\x08protocol\x18\x03 \x01(\x0e\x32\x10.io.PassProtocol\x12!\n\rpersonDetails\x18\x04 \x01(\x0b\x32\n.io.Person\x12\x1e\n\x08metadata\x18\x05 \x01(\x0b\x32\x0c.io.Metadata\x12,\n\nrecordData\x18\x06 \x03(\x0b\x32\x18.io.Pass.RecordDataEntry\x12\x12\n\nexternalId\x18\x07 \x01(\t\x1a\x31\n\x0fRecordDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  PassOverrides = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.PassOverrides").msgclass
  PassOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.PassOptions").msgclass
  Pass = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Pass").msgclass
end
