# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/personal.proto

require 'google/protobuf'

require 'io/common/common_objects_pb'


descriptor_data = "\n\x18io/common/personal.proto\x12\x02io\x1a\x1eio/common/common_objects.proto\"\xd9\x02\n\x06Person\x12\x0f\n\x07surname\x18\x01 \x01(\t\x12\x10\n\x08\x66orename\x18\x02 \x01(\t\x12\x12\n\notherNames\x18\x03 \x03(\t\x12\x12\n\nsalutation\x18\x04 \x01(\t\x12\x0e\n\x06suffix\x18\x05 \x01(\t\x12\x13\n\x0b\x64isplayName\x18\x06 \x01(\t\x12\x1a\n\x06gender\x18\x07 \x01(\x0e\x32\n.io.Gender\x12\x1d\n\x0b\x64\x61teOfBirth\x18\x08 \x01(\x0b\x32\x08.io.Date\x12\x14\n\x0c\x65mailAddress\x18\t \x01(\t\x12\x14\n\x0cmobileNumber\x18\n \x01(\t\x12\x12\n\nexternalId\x18\x0b \x01(\t\x12\x30\n\x0b\x65xternalIds\x18\x0c \x03(\x0b\x32\x1b.io.Person.ExternalIdsEntry\x1a\x32\n\x10\x45xternalIdsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8e\x01\n\x07\x41\x64\x64ress\x12\x14\n\x0c\x61\x64\x64ressLine1\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x64\x64ressLine2\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x64\x64ressLine3\x18\x03 \x01(\t\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t\x12\r\n\x05state\x18\x05 \x01(\t\x12\x0f\n\x07zipCode\x18\x06 \x01(\t\x12\x13\n\x0b\x63ountryCode\x18\x07 \x01(\t\"\\\n\rPersonRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nexternalId\x18\x02 \x01(\t\x12\x0f\n\x07\x63lassId\x18\x03 \x01(\t\x12\x1a\n\x06person\x18\x04 \x01(\x0b\x32\n.io.Person*-\n\x06Gender\x12\r\n\tNOT_KNOWN\x10\x00\x12\x08\n\x04MALE\x10\x01\x12\n\n\x06\x46\x45MALE\x10\x02\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  Person = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Person").msgclass
  Address = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Address").msgclass
  PersonRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.PersonRequest").msgclass
  Gender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Gender").enummodule
end
