# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/project.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/protocols_pb'
require 'io/common/template_pb'


descriptor_data = "\n\x17io/common/project.proto\x12\x02io\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19io/common/protocols.proto\x1a\x18io/common/template.proto\"\xc3\x01\n\x07Project\x12\"\n\x08protocol\x18\x01 \x01(\x0e\x32\x10.io.PassProtocol\x12\x0f\n\x07\x63lassId\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tshortCode\x18\x04 \x01(\t\x12+\n\x07\x63reated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06secret\x18\x06 \x01(\t\x12\x0b\n\x03key\x18\x07 \x01(\t\x12\x18\n\x10\x65ncryptedClassId\x18\t \x01(\t\"\\\n\x18ProjectByShortCodeResult\x12\x1c\n\x07project\x18\x01 \x01(\x0b\x32\x0b.io.Project\x12\"\n\x08template\x18\x02 \x01(\x0b\x32\x10.io.PassTemplate\"8\n\x13ProjectStatusFilter\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.io.ProjectStatus*\xe4\x01\n\rProjectStatus\x12\x15\n\x11NO_PROJECT_STATUS\x10\x00\x12&\n\"PROJECT_ACTIVE_FOR_OBJECT_CREATION\x10\x01\x12(\n$PROJECT_DISABLED_FOR_OBJECT_CREATION\x10\x02\x12\x11\n\rPROJECT_DRAFT\x10\x04\x12\x15\n\x11PROJECT_PUBLISHED\x10\x08\x12\x13\n\x0fPROJECT_PRIVATE\x10\x10\x12\x16\n\x12PROJECT_OVER_QUOTA\x10 \x12\x13\n\x0fPROJECT_DELETED\x10@BG\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  Project = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Project").msgclass
  ProjectByShortCodeResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.ProjectByShortCodeResult").msgclass
  ProjectStatusFilter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.ProjectStatusFilter").msgclass
  ProjectStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.ProjectStatus").enummodule
end
