# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/protocols.proto

require 'google/protobuf'


descriptor_data = "\n\x19io/common/protocols.proto\x12\x02io*\xa0\x01\n\x0cPassProtocol\x12\x1c\n\x18PASS_PROTOCOL_DO_NOT_USE\x10\x00\x12\x10\n\x0cRAW_PROTOCOL\x10\x01\x12\x0f\n\x0bV1_PROTOCOL\x10\x02\x12\x13\n\x0f\x46LIGHT_PROTOCOL\x10\x03\x12\x0e\n\nMEMBERSHIP\x10\x64\x12\x15\n\x11SINGLE_USE_COUPON\x10\x65\x12\x13\n\x0f\x45VENT_TICKETING\x10\x66*\x8e\x02\n\x14ProtocolCommonEvents\x12%\n!PROTOCOL_COMMON_EVENTS_DO_NOT_USE\x10\x00\x12\x18\n\x14\x45VENT_OBJECT_CREATED\x10\x01\x12\x18\n\x14\x45VENT_OBJECT_UPDATED\x10\x02\x12\x18\n\x14\x45VENT_OBJECT_EXPIRED\x10\x03\x12\x18\n\x14\x45VENT_OBJECT_DELETED\x10\x04\x12\x15\n\x11\x45VENT_PASS_ISSUED\x10\x05\x12\x18\n\x14\x45VENT_PASS_INSTALLED\x10\x06\x12\x1a\n\x16\x45VENT_PASS_UNINSTALLED\x10\x07\x12\x1a\n\x16\x45VENT_PASS_INVALIDATED\x10\x08\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  PassProtocol = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.PassProtocol").enummodule
  ProtocolCommonEvents = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.ProtocolCommonEvents").enummodule
end
