# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/proximity.proto

require 'google/protobuf'

require 'io/common/localization_pb'


descriptor_data = "\n\x19io/common/proximity.proto\x12\x02io\x1a\x1cio/common/localization.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa7\x03\n\x06\x42\x65\x61\x63on\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x1b\n\x05major\x18\x04 \x01(\rB\x0c\x92\x41\tY\x00\x00\x00\x00\xe0\xff\xef@\x12\x1b\n\x05minor\x18\x05 \x01(\rB\x0c\x92\x41\tY\x00\x00\x00\x00\xe0\xff\xef@\x12\x19\n\x11lockScreenMessage\x18\x06 \x01(\t\x12\x37\n\x1alocalizedLockScreenMessage\x18\x07 \x01(\x0b\x32\x13.io.LocalizedString\x12\x10\n\x08position\x18\x08 \x01(\r:\xd4\x01\x92\x41\xd0\x01\n\xcd\x01*\x06\x42\x65\x61\x63on2\xa7\x01\x41 beacon record enables the pass to push a message to the lock screen when the user is in close proximity with the beacon. Beacons are currently only supported by iOS.\xd2\x01\x04uuid\xd2\x01\x11lockScreenMessage\"\x94\x03\n\x0bGPSLocation\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0b\n\x03lon\x18\x04 \x01(\x01\x12\x0b\n\x03\x61lt\x18\x05 \x01(\x05\x12\x19\n\x11lockScreenMessage\x18\x06 \x01(\t\x12\x37\n\x1alocalizedLockScreenMessage\x18\x07 \x01(\x0b\x32\x13.io.LocalizedString\x12\x10\n\x08position\x18\x08 \x01(\r:\xdd\x01\x92\x41\xd9\x01\n\xd6\x01*\x0cGPS Location2\xa4\x01\x41 location record enables the pass to be pushed to the lock screen when the user is in near the location. For iOS users, a customized message can also be displayed.\xd2\x01\x03lat\xd2\x01\x04long\xd2\x01\x11lockScreenMessage\"!\n\x0cRelevantDate\x12\x11\n\ttimestamp\x18\x01 \x01(\rBG\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  Beacon = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Beacon").msgclass
  GPSLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.GPSLocation").msgclass
  RelevantDate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.RelevantDate").msgclass
end
