# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/transaction.proto

require 'google/protobuf'

require 'io/common/common_objects_pb'
require 'io/common/proximity_pb'


descriptor_data = "\n\x1bio/common/transaction.proto\x12\x02io\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1eio/common/common_objects.proto\x1a\x19io/common/proximity.proto\"\x94\x04\n\x0bTransaction\x12\x13\n\x0breferenceId\x18\x01 \x01(\t\x12\x12\n\ntotalPrice\x18\x02 \x01(\x02\x12!\n\norderItems\x18\x03 \x03(\x0b\x32\r.io.OrderItem\x12\x10\n\x08\x64iscount\x18\x04 \x01(\x02\x12\'\n\rdiscountItems\x18\x05 \x03(\x0b\x32\x10.io.DiscountItem\x12\x15\n\rserviceCharge\x18\x06 \x01(\x02\x12\x10\n\x08totalTax\x18\x07 \x01(\x02\x12\x12\n\nfinalPrice\x18\x08 \x01(\x02\x12\x1a\n\x12roundingDifference\x18\t \x01(\x02\x12\x12\n\nisRefunded\x18\n \x01(\x08\x12\x1b\n\ttimestamp\x18\x0b \x01(\x0b\x32\x08.io.Date\x12\x10\n\x08\x63urrency\x18\x0c \x01(\t\x12!\n\x08location\x18\r \x01(\x0b\x32\x0f.io.GPSLocation\x12\x19\n\x11transactionSource\x18\x0e \x01(\t:\xa3\x01\x92\x41\x9f\x01\n\x9c\x01*\x0bTransaction2mTransaction information for member programs that want to show latest transactions on back of the member card.\xd2\x01\ttimestamp\xd2\x01\x06\x61mount\xd2\x01\x08\x63urrency\"a\n\x0c\x44iscountItem\x12\x14\n\x0c\x64iscountCode\x18\x01 \x01(\t\x12\x13\n\x0bvoucherCode\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x02\x12\x10\n\x08itemName\x18\x05 \x01(\tJ\x04\x08\x03\x10\x04\"Y\n\tOrderItem\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x02\x12\x0b\n\x03tax\x18\x02 \x01(\x02\x12\x10\n\x08itemName\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x0b\n\x03sku\x18\x05 \x01(\tBG\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Io
  Transaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.Transaction").msgclass
  DiscountItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.DiscountItem").msgclass
  OrderItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.OrderItem").msgclass
end
