# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/member/event.proto

require 'google/protobuf'


descriptor_data = "\n\x15io/member/event.proto\x12\x07members\"\x8b\x02\n\x0c\x45ventDetails\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\x12\x0b\n\x03\x61lt\x18\x04 \x01(\x05\x12\x17\n\x0f\x65xternalEventId\x18\x05 \x01(\t\x12\x18\n\x10\x65xternalDeviceId\x18\x06 \x01(\t\x12\x19\n\x11\x65xternalServiceId\x18\x07 \x01(\t\x12\x35\n\x08metaData\x18\x08 \x03(\x0b\x32#.members.EventDetails.MetaDataEntry\x12\r\n\x05notes\x18\t \x01(\t\x1a/\n\rMetaDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42_\n\x18\x63om.passkit.grpc.MembersZ,stash.passkit.com/io/model/sdk/go/io/members\xaa\x02\x14PassKit.Grpc.Membersb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Members
  EventDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.EventDetails").msgclass
end
