# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/member/tier.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'io/common/localization_pb'
require 'io/common/common_objects_pb'
require 'io/common/expiry_pb'


descriptor_data = "\n\x14io/member/tier.proto\x12\x07members\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1cio/common/localization.proto\x1a\x1eio/common/common_objects.proto\x1a\x16io/common/expiry.proto\"\xa3\x06\n\x04Tier\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttierIndex\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12*\n\rlocalizedName\x18\x04 \x01(\x0b\x32\x13.io.LocalizedString\x12\x19\n\x11secondaryTierName\x18\x05 \x01(\t\x12\x37\n\x1alocalizedSecondaryTierName\x18\x06 \x01(\x0b\x32\x13.io.LocalizedString\x12\x11\n\tprogramId\x18\x07 \x01(\t\x12\x16\n\x0epassTemplateId\x18\x08 \x01(\t\x12\x1a\n\x12tierUpgradeMessage\x18\t \x01(\t\x12\x38\n\x1blocalizedTierUpgradeMessage\x18\n \x01(\x0b\x32\x13.io.LocalizedString\x12\x1c\n\x14tierDowngradeMessage\x18\x0b \x01(\t\x12:\n\x1dlocalizedTierDowngradeMessage\x18\x0c \x01(\x0b\x32\x13.io.LocalizedString\x12+\n\x07\x63reated\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fpointsOverdrawn\x18\x0f \x01(\x08\x12 \n\x18secondaryPointsOverdrawn\x18\x10 \x01(\x08\x12*\n\x0e\x65xpirySettings\x18\x11 \x01(\x0b\x32\x12.io.ExpirySettings\x12\x10\n\x08timezone\x18\x12 \x01(\t\x12&\n\x12\x61llowTierEnrolment\x18\x13 \x01(\x0b\x32\n.io.PkBool\x12\x11\n\tshortCode\x18\x14 \x01(\t:\x84\x01\x92\x41\x80\x01\n~*\x04Tier2ATier allows a company to override certain details in the program.\xd2\x01\x02id\xd2\x01\ttierIndex\xd2\x01\tprogramId\xd2\x01\x04name\xd2\x01\x0epassTemplateId\"5\n\x10TierRequestInput\x12\x11\n\tprogramId\x18\x01 \x01(\t\x12\x0e\n\x06tierId\x18\x02 \x01(\tB_\n\x18\x63om.passkit.grpc.MembersZ,stash.passkit.com/io/model/sdk/go/io/members\xaa\x02\x14PassKit.Grpc.Membersb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Members
  Tier = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.Tier").msgclass
  TierRequestInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("members.TierRequestInput").msgclass
end
