# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc-gen-openapiv2/options/annotations.proto

require "google/protobuf"
require "google/protobuf/descriptor_pb"
require "protoc-gen-openapiv2/options/openapiv2_pb"

descriptor_data = "\n.protoc-gen-openapiv2/options/annotations.proto\x12)grpc.gateway.protoc_gen_openapiv2.options\x1A google/protobuf/descriptor.proto\x1A,protoc-gen-openapiv2/options/openapiv2.proto:~\n\x11openapiv2_swagger\x12\x1C.google.protobuf.FileOptions\x18\x92\b \x01(\v22.grpc.gateway.protoc_gen_openapiv2.options.SwaggerR\x10openapiv2Swagger:\x86\x01\n\x13openapiv2_operation\x12\x1E.google.protobuf.MethodOptions\x18\x92\b \x01(\v24.grpc.gateway.protoc_gen_openapiv2.options.OperationR\x12openapiv2Operation:~\n\x10openapiv2_schema\x12\x1F.google.protobuf.MessageOptions\x18\x92\b \x01(\v21.grpc.gateway.protoc_gen_openapiv2.options.SchemaR\x0Fopenapiv2Schema:u\n\ropenapiv2_tag\x12\x1F.google.protobuf.ServiceOptions\x18\x92\b \x01(\v2..grpc.gateway.protoc_gen_openapiv2.options.TagR\fopenapiv2Tag:~\n\x0Fopenapiv2_field\x12\x1D.google.protobuf.FieldOptions\x18\x92\b \x01(\v25.grpc.gateway.protoc_gen_openapiv2.options.JSONSchemaR\x0Eopenapiv2FieldBHZFgithub.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/optionsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)
