# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/flights/a_rpc.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/empty_pb'
require 'io/flights/boarding_pass_pb'
require 'io/flights/airport_pb'
require 'io/flights/flight_pb'
require 'io/flights/flight_designator_pb'
require 'io/flights/carrier_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/flights/a_rpc.proto", :syntax => :proto3) do
  end
end

module Flights
end
