# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/flights/airport.proto

require 'google/protobuf'

require 'io/common/localization_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/flights/airport.proto", :syntax => :proto3) do
    add_message "flights.Port" do
      optional :iataAirportCode, :string, 1
      optional :icaoAirportCode, :string, 2
      optional :cityName, :string, 3
      optional :localizedCityName, :message, 4, "io.LocalizedString"
      optional :airportName, :string, 5
      optional :localizedAirportName, :message, 6, "io.LocalizedString"
      optional :countryCode, :string, 7
      optional :timezone, :string, 8
    end
    add_message "flights.AirportCode" do
      optional :airportCode, :string, 1
    end
  end
end

module Flights
  Port = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.Port").msgclass
  AirportCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.AirportCode").msgclass
end
