# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/flights/barcode.proto

require 'google/protobuf'

require 'io/common/common_objects_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/flights/barcode.proto", :syntax => :proto3) do
    add_message "flights.ConditionalItems" do
      optional :passengerDescription, :enum, 1, "flights.PassengerDescription"
      optional :checkInSource, :enum, 2, "flights.Source"
      optional :boardingPassIssuanceSource, :enum, 3, "flights.Source"
      optional :boardingPassIssueDate, :message, 4, "io.Date"
      optional :documentType, :enum, 5, "flights.DocType"
      optional :boardingPassIssuer, :string, 6
      repeated :baggageTagNumber, :string, 7
      optional :selecteeIndicator, :enum, 8, "flights.SelecteeIndicator"
      optional :internationalDocVerification, :enum, 9, "flights.InternationalDocVerification"
      optional :idadIndicator, :enum, 10, "flights.IDADIndicator"
      optional :fastTrack, :enum, 11, "flights.FastTrack"
    end
    add_enum "flights.PassengerStatus" do
      value :ISSUED_NOT_CHECKED_IN, 0
      value :ISSUED_CHECKED_IN, 1
      value :BAGGAGE_CHECKED_PASSENGER_NOT_CHECKED_IN, 2
      value :BAGGAGE_CHECKED_PASSENGER_CHECKED_IN, 3
      value :PASSENGER_PASSED_SECURITY_CHECK, 4
      value :PASSENGER_PASSED_GATE, 5
      value :TRANSIT, 6
      value :STANDBY, 7
      value :BOARDING_DATA_REVALIDATION_DONE, 8
      value :ORIGINAL_BOARDING_LINE_USED_AT_TICKET_ISSUANCE, 9
      value :UP_OR_DOWN_GRADING_REQUIRED, 10
    end
    add_enum "flights.PassengerDescription" do
      value :ADULT, 0
      value :MALE, 1
      value :FEMALE, 2
      value :CHILD, 3
      value :INFANT, 4
      value :NO_PASSENGER, 5
      value :ADULT_WITH_INFANT, 6
      value :UNACCOMPANIED_MINOR, 7
    end
    add_enum "flights.Source" do
      value :W, 0
      value :K, 1
      value :X, 2
      value :R, 3
      value :M, 4
      value :O, 5
      value :T, 6
      value :V, 7
    end
    add_enum "flights.DocType" do
      value :B, 0
      value :I, 1
    end
    add_enum "flights.InternationalDocVerification" do
      value :NOT_REQUIRED, 0
      value :REQUIRED, 1
      value :COMPLETED, 2
    end
    add_enum "flights.IDADIndicator" do
      value :NONE, 0
      value :IDN1, 1
      value :IDN2, 2
      value :IDB1, 3
      value :IDB2, 4
      value :AD, 5
      value :DG, 6
      value :DM, 7
      value :GE, 8
      value :IG, 9
      value :RG, 10
      value :UD, 11
      value :ID, 12
      value :IDFS1, 13
      value :IDFS2, 14
      value :IDR1, 15
      value :IDR2, 16
    end
    add_enum "flights.SelecteeIndicator" do
      value :NOT_SELECTEE, 0
      value :SELECTEE, 1
      value :TSA_PRECHECK, 3
    end
    add_enum "flights.FastTrack" do
      value :N, 0
      value :Y, 1
    end
  end
end

module Flights
  ConditionalItems = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.ConditionalItems").msgclass
  PassengerStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.PassengerStatus").enummodule
  PassengerDescription = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.PassengerDescription").enummodule
  Source = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.Source").enummodule
  DocType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.DocType").enummodule
  InternationalDocVerification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.InternationalDocVerification").enummodule
  IDADIndicator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.IDADIndicator").enummodule
  SelecteeIndicator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.SelecteeIndicator").enummodule
  FastTrack = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.FastTrack").enummodule
end
