# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/flights/boarding_pass.proto

require 'google/protobuf'

require 'io/flights/passenger_pb'
require 'io/flights/barcode_pb'
require 'io/flights/cabin_codes/cabin_codes_pb'
require 'io/common/common_objects_pb'
require 'io/common/proximity_pb'
require 'io/common/links_pb'
require 'io/common/metrics_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/flights/boarding_pass.proto", :syntax => :proto3) do
    add_message "flights.BoardingPassRecord" do
      optional :id, :string, 1
      optional :operatingCarrierPNR, :string, 2
      repeated :relatedPNRs, :string, 3
      optional :ticketNumber, :string, 4
      optional :ticketLeg, :int32, 5
      optional :boardingPoint, :string, 6
      optional :deplaningPoint, :string, 7
      optional :carrierCode, :string, 8
      optional :flightNumber, :string, 9
      optional :departureDate, :message, 11, "io.Date"
      optional :passenger, :message, 12, "flights.Passenger"
      optional :class, :string, 13
      optional :compartmentCode, :enum, 14, "cabin_codes.CompartmentCode"
      optional :seatNumber, :string, 15
      optional :sequenceNumber, :int32, 16
      optional :boardingGroup, :string, 17
      optional :boardingPosition, :string, 18
      optional :freeBaggageAllowance, :string, 19
      optional :carryOnAllowance, :string, 20
      repeated :ssrCodes, :string, 21
      optional :osi, :string, 22
      optional :remarks, :string, 23
      optional :passengerStatus, :enum, 24, "flights.PassengerStatus"
      optional :conditionalItems, :message, 25, "flights.ConditionalItems"
      optional :barcodePayload, :string, 26
      optional :securityImage, :string, 27
      optional :privilegeImage, :string, 28
      optional :footerImage, :string, 29
      repeated :locationMessages, :message, 30, "io.GPSLocation"
      repeated :beaconMessages, :message, 31, "io.Beacon"
      repeated :links, :message, 32, "io.Link"
      optional :barcodeAdditionalData, :string, 33
      optional :infantPassId, :string, 34
      optional :additionalDataItems, :message, 35, "io.DataItems"
      optional :metadata, :message, 36, "io.Metadata"
    end
    add_message "flights.BoardingPassRecordRequestByTicketNumber" do
      optional :ticketNumber, :string, 1
      optional :ticketLeg, :int32, 2
      optional :boardingPoint, :string, 3
    end
    add_message "flights.BoardingPassRecordRequestByIndex" do
      optional :carrierCode, :string, 1
      optional :flightNumber, :string, 2
      optional :departureDate, :message, 3, "io.Date"
      optional :boardingPoint, :string, 4
      optional :sequenceNumber, :int32, 5
    end
    add_message "flights.BoardingPassRequest" do
      repeated :format, :enum, 5, "io.PassBundleFormat"
      oneof :request do
        optional :ticketNumber, :message, 1, "flights.BoardingPassRecordRequestByTicketNumber"
        optional :index, :message, 2, "flights.BoardingPassRecordRequestByIndex"
        optional :pnr, :message, 3, "flights.BoardingPassesForBookingRequest"
        optional :passId, :message, 4, "io.Id"
      end
    end
    add_message "flights.BoardingPassRecordRequest" do
      oneof :request do
        optional :ticketNumber, :message, 1, "flights.BoardingPassRecordRequestByTicketNumber"
        optional :index, :message, 2, "flights.BoardingPassRecordRequestByIndex"
        optional :passId, :message, 3, "io.Id"
      end
    end
    add_message "flights.BoardingPassesForBookingRequest" do
      optional :pnr, :string, 1
      optional :ticketLeg, :int32, 2
      optional :boardingPoint, :string, 3
    end
    add_message "flights.BoardingPassesResponse" do
      repeated :boardingPasses, :message, 1, "io.PassBundle"
    end
  end
end

module Flights
  BoardingPassRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.BoardingPassRecord").msgclass
  BoardingPassRecordRequestByTicketNumber = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.BoardingPassRecordRequestByTicketNumber").msgclass
  BoardingPassRecordRequestByIndex = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.BoardingPassRecordRequestByIndex").msgclass
  BoardingPassRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.BoardingPassRequest").msgclass
  BoardingPassRecordRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.BoardingPassRecordRequest").msgclass
  BoardingPassesForBookingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.BoardingPassesForBookingRequest").msgclass
  BoardingPassesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.BoardingPassesResponse").msgclass
end
