# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/flights/carrier.proto

require 'google/protobuf'

require 'io/common/localization_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/flights/carrier.proto", :syntax => :proto3) do
    add_message "flights.Carrier" do
      optional :iataCarrierCode, :string, 1
      optional :icaoCarrierCode, :string, 2
      optional :iataAccountingCode, :int32, 3
      optional :airlineName, :string, 4
      optional :localizedAirlineName, :message, 5, "io.LocalizedString"
      optional :passTypeIdentifier, :string, 6
      optional :privateKeyId, :string, 7
    end
    add_message "flights.CarrierCode" do
      optional :carrierCode, :string, 1
    end
  end
end

module Flights
  Carrier = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.Carrier").msgclass
  CarrierCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.CarrierCode").msgclass
end
