# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/flights/flight_designator.proto

require 'google/protobuf'

require 'io/common/common_objects_pb'
require 'io/common/proximity_pb'
require 'io/common/links_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("io/flights/flight_designator.proto", :syntax => :proto3) do
    add_message "flights.FlightDesignator" do
      optional :carrierCode, :string, 1
      optional :flightNumber, :string, 2
      optional :validFrom, :message, 3, "io.Date"
      optional :revision, :uint32, 4
      optional :active, :bool, 5
      optional :schedule, :message, 6, "flights.FlightSchedule"
      optional :operatingCarrierCode, :string, 7
      optional :operatingFlightNumber, :string, 8
      repeated :codeShareFlightNumbers, :string, 9
      optional :origin, :string, 10
      optional :destination, :string, 11
      repeated :transitPoints, :string, 12
      optional :departureTerminal, :string, 13
      optional :arrivalTerminal, :string, 14
      repeated :transitTerminals, :string, 15
      optional :boardingPolicy, :enum, 16, "flights.BoardingPolicy"
      optional :seatClassPolicy, :enum, 17, "flights.SeatClassPolicy"
      repeated :alerts, :enum, 18, "flights.FlightAlerts"
      optional :passTemplateId, :string, 19
      optional :autoInvalidateAfter, :uint32, 20
      optional :autoInvalidateCancelledPasses, :bool, 21
      repeated :locationMessages, :message, 22, "io.GPSLocation"
      repeated :beaconMessages, :message, 23, "io.Beacon"
      repeated :defaultLinks, :message, 24, "io.Link"
      optional :ConditionalItems, :bool, 25
      optional :BarcodeAdditionalData, :string, 26
    end
    add_message "flights.FlightDesignatorRequest" do
      optional :carrierCode, :string, 1
      optional :flightNumber, :string, 2
      optional :revision, :uint32, 3
    end
    add_message "flights.FlightSchedule" do
      optional :monday, :message, 1, "flights.FlightTimes"
      optional :tuesday, :message, 2, "flights.FlightTimes"
      optional :wednesday, :message, 3, "flights.FlightTimes"
      optional :thursday, :message, 4, "flights.FlightTimes"
      optional :friday, :message, 5, "flights.FlightTimes"
      optional :saturday, :message, 6, "flights.FlightTimes"
      optional :sunday, :message, 7, "flights.FlightTimes"
    end
    add_message "flights.FlightTimes" do
      optional :scheduledDepartureTime, :message, 1, "io.Time"
      optional :boardingTime, :message, 2, "io.Time"
      optional :gateClosingTime, :message, 3, "io.Time"
      optional :scheduledArrivalTime, :message, 4, "io.Time"
    end
    add_enum "flights.FlightAlerts" do
      value :NO_ALERTS, 0
      value :ALL_ALERTS, 1
      value :DEPARTURE_GATE_ALERT, 2
      value :DEPARTURE_TIME_ALERT, 4
      value :ARRIVAL_GATE_ALERT, 8
      value :ARRIVAL_TIME_ALERT, 16
      value :BAGGAGE_BELT_ALERT, 32
    end
    add_enum "flights.BoardingPolicy" do
      value :BOARDING_POLICY_UNSPECIFIED, 0
      value :ZONE_BASED, 1
      value :GROUP_BASED, 2
      value :BOARDING_POLICY_OTHER, 3
    end
    add_enum "flights.SeatClassPolicy" do
      value :SEAT_CLASS_POLICY_UNSPECIFIED, 0
      value :CABIN_BASED, 1
      value :CLASS_BASED, 2
      value :TIER_BASED, 3
      value :SEAT_CLASS_POLICY_OTHER, 4
    end
    add_enum "flights.Authority" do
      value :IATA, 0
      value :ICAO, 1
    end
  end
end

module Flights
  FlightDesignator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.FlightDesignator").msgclass
  FlightDesignatorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.FlightDesignatorRequest").msgclass
  FlightSchedule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.FlightSchedule").msgclass
  FlightTimes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.FlightTimes").msgclass
  FlightAlerts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.FlightAlerts").enummodule
  BoardingPolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.BoardingPolicy").enummodule
  SeatClassPolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.SeatClassPolicy").enummodule
  Authority = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("flights.Authority").enummodule
end
